<?php
/*
Plugin Name: Mesnevi-i Manevi
Plugin URI: http://wordpress.org/extend/plugins/mesnevi-i-manevi/
Description: Mevlânâ Celâleddin Rumî'nin altı ciltlik Farsça eseri, Mesnevî-i Manevî'den seçme beyitleri Türkçe olarak gösteren bir eklenti.
Version: 1.1
Author: Süleyman ÜSTÜN
Author URI: http://suleymanustun.com
*/

$mesnevi = array(
	'Dildeşinden ayrı düşen yüz türlü nağmesi bile olsa, dilsizdir. Gül solup da mevsim geçince bülbülden nağme duyamazsın.',
	'Kimin aşka eğilimi yoksa, kanatsız kuş gibidir.',
	'Rahmet kapıları dilencilere hırslarından dolayı kapandı. Zekât verilmeyince yağmur bulutu gelmez, zina artınca bulaşıcı hastalıklar artar. İçine gam ve kasvetten ne gelirse korkusuzluk ve küstahlığından gelir.',
	'Her odunun kokusu dumanından çıkar. İnleme, hastalığın çeşidini ele verir.',
	'Aşk, Allah sırlarının usturlabıdır.(Usturlab: Güneşin yüksekliğini ölçen alet) Dilin tefsiri pek aydınlatıcıdır. Fakat dile düşmeyen aşk, daha nurludur.',
	'Vakit keskin bir kılıçtır. Sufi, vakit oğludur. Yarın demez, anı değerlendirir.',
	'Sırların gönülde kalırsa, muradın çabuk gerçekleşir. Tohum toprağa gizlenirse yeşerir.',
	'Zahiri güzelliği ait olan aşklar aşk değildir. Onlar sonuçta utanç olurlar.',
	'Cihan dağdır, yaptıklarımız ses. Başına gelenler o sesin yankısıdır.',
	'Bu sıkıntılar çileler ocağın posayı gümüşten ayırması içindir. İyi ve kötünün imtihanı altının kaynatılıp, tortunun üste çıkmasıdır.',
	'Dünya hissi cihanın, din hissi göklerin merdivenidir. Dünya hissinin sağlığını hekimden,din hissinin sağlığını Muhammed’den iste. Dünya hissinin sağlığı vücut sağlığıdır. Din hissinin sağlığı arzuları öldürmektir.',
	'İnsan tarafgirlik, hiddet ve şehvetten şaşı olur. Hiddet ve şehvet ruhu Hak’tan ayırır. Garez gelince, hüner örtülür.',
	'Fare nin şerrini def etmeden ambara buğday koyma.',
	'Kalp huzuru olmadan namaz tamam olmaz.',
	'Beden haset evidir.',
	'Bu âlem canların hapishanesidir.',
	'Nakış ve suret manâyı görmeyi engeldir.',
	'Akıl ve zekâ kemâle ermekle Allah’a varılmaz. Yöneticiler hediye ve ihsanını çok bilmişlere değil,önlerinde acizlenenlere verirler.',
	'Manâ yüzünden yükselmek, temiz ruhlara nasiptir.',
	'Kimde dert varsa o koku almış, dermana ermiştir. Kim daha çok uyanıksa, derdi daha fazladır.',
	'Parçaların yüzü bütüne dönüktür. Bülbülün aşkı da güle.',
	'Putların anası nefistir.',
	'Ahad ve Ahmed’e yapış ki, beden ebucehilinden kurtul.',
	'Allah bir kimsenin perdesini yırtmak isterse o kişiyi temiz insanları ayıplamaya sevk eder. Ayıbını örtmek dilerse o kimse ayıplı kimseler hakkında konuşamaz hale gelir. Yardım etmek isterse, ona dua ve yakarış kapısını açar.',
	'Her ağlamanın sonu gülmektir.',
	'Akarsu nerdeyse orası yeşerir. Gözyaşı varsa rahmet gelecektir.',
	'Gam görünce istiğfar et. Çünkü gam Yaratıcı’nın emri ile tesir eder. Allah dilerse bizzat gam ve sıkıntı sana neşe bile olabilir.',
	'Fakirlik korkusu insanları hırs ve emele lokma yapmıştır.',
	'Dünya zindan biz mahpususuz; zindanı del kurtul.Ten bir gemi, dünya denizdir. Dünyayı tenine koyarsan, gemi batar. Ayaklarının altına al ki yüzüp gidesin.',
	'Âlem cesettir. İlim can.',
	'Üç şey hakkında dudağını kıpırdatma: Gittiğin yol, paran ve mezhebin.',
	'Hikmet arayanlar: Hikmet kaynağı olur. Tahsilden ve sebebe bağlanmaktan kurtulur. Bilgileri hıfzeden levh, levhi mahfuz olur, akıl ruhtan feyz alır.',
	'Heva (arzular) iman kapısının kilidi dir.',
	'İçi kötü olanın ayıbını deri örter. İçi iyi olanın aybını gayb âlemi örter.',
	'Kalemin su, kağıdın rüzgar ise ne yazarsan yaz kıymeti yoktur.',
	'Manâsız söz; suya yazılan yazıdır.',
	'Gözün nuru gönül nurudur.',
	'Kaza gelince bilgi ve tedbir uykuya yatar.',
	'Allah insana akıbetine göre isim verir. Halk Ömer’i müşrik bilirdi.Ama Allah ezelde onu mümin yazdı. Mümin oldu.',
	'Kaza seni gece gibi sarsa da elinden tutacak olan yine odur. Seni emin kılmak için Allah’ın bela ile korkutmasını da bir çeşit yardım bil.',
	'Sağlık; zıtların barışıdır. Aralarında savaş varsa bedene ölüm gelir.',
	'Zalimin zulmü karanlık kuyudur. Sonunda içinde boğulur.',
	'İnsanlardan gördüğün zulümler senin huyundur. Sen kendi huyunu onların aynasında seyredersin.',
	'Ey gam ateşine dalan! Ateşe azar azar nur serp de nur olsun.',
	'Dünya; dedikodu, tartışma ve bahis kuyusudur. Bu kuyuya düşersen sağlam çıkamazsın.',
	'Üstünlükler ve durumların değişmesini Hak’tan bil.',
	'Birkaç gün su içmeyi bırak. Ağzını ebediyet şarabına daldır ki hakikât içesin.',
	'Cehennem bu nefistir. Bizim nefsimiz ateşten parçadır. Parça bütünü özler. Nefsin hedefi de ait olduğu cehenneme bizi çekmektir.',
	'Ok gibi doğru olursan, hiçbir yay seni tutamaz. Hakça ol ki, nefis yayından hakikâte fırla.',
	'İnsan, gözden ibarettir. Göz ise dostu gören gözdür.',
	'Hak’tan korkup takva yolundan tutandan cinler ve insanlar korkarlar.',
	'Ekmek sofrada cansızdır. Vücuda girince neşeli ruh olur.',
	'Allah’ın yaratması bizim işlerimizi meydana getirir. Bizim işlerimiz Allah işlerinin eseridir.',
	'Allah Adem’e \'Senin suçunu da ben takdir ettim. Ama sen suçun tamamını üstüne alıp tevbe ettin. Niye, Rabb’im bunu sen yaptırdın demedin’dedi. Adem ’korktum, edep dışına çıkamazdım’ dedi. Allah’işte o edebin sebebi ile biz seni koruduk ve kayırdık’dedi.',
	'Hürmet eden, hürmet görür.',
	'Akıl hakim iken Ömer’le Ebulhakem bir idi. Ömer can âlemine geçti Halife oldu. Ebulhakem akıl aleminde kaldı. Ebucehil oldu.',
	'Kuran’ın hükümlerini tutar,kıssalarından hisse alırsan can kuşuna ten kafesi dar gelir.',
	'Halk arasında meşhur olmak, sırlara ermeye engeldir. Şöhretten kurtulmaya bak.',
	'Dostların sevgiliyi anması sevgiliye ne mutludur.',
	'Allah’ım kahrına da, lütfuna da hakkı ile âşıkız.',
	'Dil çakmaktaşı ve demiri gibidir. Dilden çıkan ateş olur.',
	'Şeker gibi söz söylemek istersen helva yemeği bırak, sabret.Firaset sahiplerinin hırsı sabra, çocukların hırsı helvayadır. Sabreden arşa çıkar, helva yiyen yerde kalır.',
	'Kâmil insan toprak tutsa altın olur, eksik insan altın tutsa toprak olur.',
	'Söze kulaktan gir.(Önce dinle)',
	'Adem Allah’ın azabından ağlamakla kurtuldu.',
	'Helal lokma, nuru ve olgunluğu arttırır. İlim, hikmet, aşk, incelik helal lokmadan doğar. Lokma tohumdur; mahsulü fikir. Lokma denizdir; incisi fikir.',
	'Ağızdan bir kere çıkan söz; yaydan çıkan ok gibidir.',
	'Canını yak ki, tenin aydınlansın.',
	'Padişahlar önlerinde eğilene ikram ederler. Çok bilenlere değil.',
	'Kim seviyorsa, bil ki seviliyordur.',
	'Susuzlar suyu arar, su da susuzları.',
	'Hakk’a dalan doymaz, daha çok dalmak ister.',
	'Âşıkların hayatı ölümdür. Gönül, gönül verilerek alınır.',
	'Ucuz kazanan, ucuz verir. İnci çocuğun eline geçerse onu bir somun ekmeğe satar.',
	'İki deniz olan gözlerin incilerle dolsun istersen, gam toprağından gözüne sürme çek de ağla.',
	'Dünyanın lütfu ve yaltaklanması hoş bir lokmadır. Ama az ye. Çünkü o lokma ateştendir.',
	'Kınanmak; kaynatılmış ilaç gibidir.',
	'Nefis övüldükçe firavunlaşır. Alçakgönüllü ol, büyüklenme.',
	'Yusuf gibi güzel olamadıysan bari Yakup gibi ağlamayı öğren.',
	'Niyaz ve yoksullukta ölü gibi ol.',
	'Nebi;’bahar yelinden yararlanın,güz yelinden sakının’ dedi. Güz; nefis ve hevadır. Bahar akıl ve ruh. Güz şeytanı fısıldar. Bahar ise Evliya sözüdür.',
	'Bu âlemin direği gaflettir. Akıllılık ve uyanıklık öbür âlemdendir. Bunlar sana galip gelirse bu âlem gözünde alçalır. Akıllılık güneş, hırs buzdur. Akıllılık su, dünya kirdir.',
	'Allah kimi kendine davet ederse, o kişi dünya işlerinden vazgeçmeye başlar.',
	'Geçmişe üzülmek, gelecekten tedirgin olmak, Allah’la arandaki perdedir. O perdeyi ateşe at ki ardından Allah görünsün.',
	'Aşığın vergisi, can vermektir. Hak uğruna ekmek verene ekmek verilir. Can verene can katılır.',
	'Sel ister bulanık olsun, ister saf olsun madem ki geçicidir, onu konuşarak vakit öldürme. Dünya malı sele benzer.',
	'Bütün yaratılanlar Allah’ın ailesidir. Allah da ne güzel aile reisi!.',
	'Mal ve para külah gibidir. Külaha keller sığınır.',
	'Yoksullar mal ve mülkün ötesinde Allah’tan pek büyük rızık alırlar. İnsanlar onları anlamaz, sözlere değer vermez.',
	'Peygamber’fakirlik övüncümdür’dedi.',
	'Yoksulluğa sabret, gam ve kederi bırak artık. Yüce Allah’ın ululuğu yoksulluktur.',
	'Benim sözlerim can memesinde süttür. Emen olmadıkça güzelce gelmez.Dinleyen susuz ve arayıcı olursa vaiz ölü de olsa söz söyler .',
	'Aşağılık kişi yücelerin düşmanıdır.',
	'Allah kadını erkeğe yoldaş yarattı. Adem nasıl olur da Havva’dan ayrı kalır. Görünüşte su, ateşten üstündür. Görünüşte erkek kadına üstündür. Ama gerçekte su, ateşe konunca fokur fokur kaynar. Gerçekte erkekler mağluptur. Mağlupluk muhabbet vesilesi olacaksa ne mutlu mağluplara!.',
	'Sevgi ve merhamet, insanlık; hiddet ve şehvet, hayvanlıktır.',
	'Kadın Hak nurudur.Sevgili değil. Kadın sanki yaratıcıdır. Yaratılmış değil.',
	'Barış dalgaları gönül kirlerini giderir. Sevgi acıları tatlıya çeker. Sevgilerin aslı hak yola gitmektir.',
	'Sıradan otlar, bir ayda yetişir. Gül yetiştirmek istersen bir yıl bekleyeceksin.',
	'Su korukta ekşidir, üzümde tatlı olur, şarapta haram olur, sirkede helal olur.',
	'Görünüşteki iyilikler, gizli sevgilerin alemetidir .',
	'Akrabalık sevgiyi bildirir.',
	'Sevgi, insanı kör ve sağır eder.',
	'Gözlerini heva ve hevesten yum.',
	'Yoksulluk aynadır. Yoksula olan tavrına göre kendini gör. Cimri misin cömert misin anlarsın.',
	'Herkes Hakk’ı işitemez. Her kuş bütün inciri yutamaz.',
	'İstetmeden vermeye bak.',
	'Yöneticilerin huyu halka tesir eder. Gökyüzü yeşil ise, yer yeşerir. Gökyüzü kara ise yere yıldırımlar yağar.',
	'Deniz ; ölüyü üstünde taşır, diriyi boğmak ister.Nefis sıfatlarını öldür ki hakikât sırlarını denizi seni üstünde taşısın.',
	'Manâ kapısını tıklatırsan, açarlar.Fikir ve mantık kanadını terk et ki, sırların şahini olasın.',
	'Görüntü ibadete engeldir. Görüntüyü bırak manâya bak.',
	'Gam ve kederin anahtarı sabırdır. Endişe etmekten sakın, sakin ol. İlacın başı perhizdir. Düşünce ve mantık perhizi yap ki, can kuvvetini göresin.Kaşınmak uyuza ilaç olmaz,sadece kaşıntıyı artırır.',
	'Süslenen kişi, kendini göstermek ister. Ahirete dünyadan ibadet süsü sürmemişsen kendini Allah’a nasıl göstereceksin!.',
	'Çiçek dökülünce meyva çıkar. Ten harap olunca can görünür',
	'Heva ve hevesle az dost ol.',
	'Aslanlığına güvenme. Ümit gölgesine sığın',
	'Dünya malı Allah’ın tebessümüdür. Ona bak ama, sarhoş olacak kadar değil.',
	'Hayallerimiz geniş, dünya dardır.Hayale fazla dalma, sıkıntın artar.',
	'Akıllı kişi sıkıntı çekerken, harap olanlardan ders alır.',
	'Aslana ancak akılsızlar yiğitlik taslar.',
	'Görüntüden geçip gönlünü arıtan, gayb sırlarına ayna olur.',
	'Başına gelen eziyetler artıyor değil mi? Buğdayı başak olsun diye toprağa attılar. Değirmende un olsun diye ezdiler.Ekmek oldu. Dişleri ile ezdiler. Ezil ki can olasın. Can veresin.',
	'Varlık yoklukta görülür. Zenginin cömertliği yoksul varsa anlaşılır.',
	'Noksanını gören, Allah’a kanatlanır. Kendini olgun sanan yerde kalır.',
	'Kasırga, ağaçları yerinden söker. Ama alçak otlara şifadır. Gönül, sende Allah’a karşı ot gibi mütevazı ol da rahmete eresin.',
	'Faziletin mihrabı şüpheli işten kaçınmak ve dünya sevgisini azaltmaktır.',
	'Heveslerinden kurtulan kişi buluğa ermiştir. Milletin çoğu ise halen çocuktur. Vehim, fikir, duygu, çocukların tahtadan atıdır. Sen ilim atına bin.İlim, gönül ehline küheylan olur, beden ehline yük olur.',
	'Kendini kendinden arıt ki, içindeki pak seni göresin.',
	'Vücut ana gibi ruha gebedir. Ölüm ruhun doğumudur.',
	'Zindandan kurtulmak istersen sevgiliye baş eğ.(Secde yap)',
	'Ümit ve korku perdesini yırtarsan gayb alemi bütün ihtişamı ile karşına çıkar.',
	'Sözden el çek ki, Allah sende Ledün ilmini meydana çıkarsın.',
	'İyilikte ve kötülükte her insanın kendisine benzer melekten bir arkadaşı vardır.',
	'Ateşten yaratılanlar, topraktan yaratılana düşmandır. Ateş suya , su ateşe düşmandır. Ateş heva, su ise dindir. Din ehlini, kin ehlinden ayır. Hak’la oturanı ara bul da onunla otur.',
	'Olayları yorumlama.Kendini yorumla.Kendine kötü de, ama gülbahçesine kötü deme. Hilm (yumuşaklık) kılıcı düşmanları yener. İlim suyu toprağı yeşertir .',
	'Allah’a kul ol, tene memur olma.',
	'Hışım, şehvet ve hırs rüzgârı namaz ehli olmayanları siler süpürür.',
	'Arzulara kul olan, Allah katında köleden beterdir.',
	'Bazı suçlar ve günahlar rahmet ve kurtuluş sebebidir. Ömer Peygamber’i öldürmeye geldi.İman etti. Âdem yasak meyve yedi. Kulluk ve dünya hayatı başladı.',
	'Bazı öldürmeler hayat verir. Bahçıvan ağaçları budamasa dallar gelişir mi?Terzi kumaşı parça parça etmese elbise çıkar mı?',
	'Yürü, kork ve kötüleri az kına. Allah takdirinin tuzağına karşı aczini bil.',
	'Hangi renk camdan bakarsan güneşi o rengte görürsün. Camı kır ki nur görünsün.',
	'Allah seni bezedi, nakşetti. Nakşı kıramazsan ruhu göremezsin. Allah’ın nakşını yine Allah’ın eliyle kır. Sevgilinin camına onun bahçesinden taş at.',
	'Amaca sabırla varılır. Acele ile değil.',
	'Öte âleme bağ olan şeyler; ağız ve boğazdır. Onları kapa da ötel',
	'Bâki nur, bu aşağılık dünyanın ardındadır. Unutma ki; süt de kan nehirlerinin içinden akarak saf oldu.',
	'Bir akıl başka bir akılla birleşirse, kötü söz ve kötü işe engel olmuş demektir. Nefis başka bir nefsle dost olursa, akıl işe yaramaz hale gelir. Akıl başka akılla birleşti mi yol görünür, nefs başka nefsle birleşti mi yol kapanır.',
	'Bilgiyle uyumak, uyanıklıktır .',
	'Ruh, ilim ve akılla dosttur.',
	'Hayvan padişahın mevkiini bilebilse, öküzle eşek de Allah ‘ı görürdü.',
	'Sabır, kurtuluşun anahtarıdır. Sabır, gözün perdesini açar; gönlü yarar açar. Gönül saf hale gelince de toprak ve su haricinde suretler görürsün.',
	'Güzel; güzeli sever.',
	'Can aynası, ancak sevgilinin yüzüdür.',
	'Mal çöptür. Ama boğazına da bir takıldı mı âb-ı hayatı içmene engel olur.',
	'Nice dualar vardır ki; helak olmanın ta kendisidir. Onun için Allah kabul etmez onları.',
	'İnsanların çoğu; insan yiyicidir. Selam verseler de pek emin olma.',
	'Aslan gibi avını kendin avla.Yabancının yaltaklanmasını, akraba desteğini falan unut.',
	'Kimsesiz olmak; adam olmayanların işve yapmasından daha iyidir.',
	'Tene yağlı ballı şeyleri verdikçe cevherini gelişmiş göremezsin.',
	'Miski tene sürme, gönle sür. Misk; Allah adıdır.',
	'Temiz söz hakikatten uzak olanlara tesir etmez. Çarpık ayakkabı çarpık ayağa uyar. Doğru olmayan gönüllere de şeytanın efsun ve efsanesi uyar.',
	'Dini, babadan bedava miras olarak buldun. Onun için şükürden baş çevirirsin. Mirasyedi, mal kıymetini ne bilsin!..',
	'Ben birisini ağlatırsam rahmetim coşar, ağlayıp taşan kişi de rahmete erer.',
	'Birine bir şey vermek istemezsem, o isteği ona göstermem.',
	'Rahmetim ağlamalara bağlıdır. Kul ağladı mı rahmet denizi dalgalanmaya başlar.',
	'Şehirler diridir. Kalıba bakma sen, onlar da hisseder.',
	'Gönlüne geçim kaygısını az koy. Eğer Hak kapısında isen korkma, ikram edilirsin.',
	'Beden, ruha otağdır .',
	'Dal, ağlayan buluttan yeşerir. Mum ağladıkça aydınlık artar.',
	'Mukallit olarak yaşama dini. Ama mukallit de ihsana nail olur.Yakını ölmese de cenazede yas edicilere de ücret verirler. Ekmek isteyen, yıllardır ‘Allah ‘ der de gönle inmemişse bu söz, mushaf taşıyan eşekten farksızdır .',
	'Gözün, aklın ve kulağın saf olsun dilersen; tamah perdesini yırt.',
	'Afetsiz, felaketsiz hiçbir köşe yoktur. Allah ‘ın halvet yerinden başka hiçbir yerde dinlenme ve rahat yoktur.',
	'Sabır, güzel hayallerle tatlılaşır.',
	'Kurtuluş ümidi imandan gelir .',
	'Sen mekânsın. Ama aslın mekânsızlıktır. Bu dükkânı kapa da ötekisi açılsın.',
	'Kim seni Hak ‘tan, hakikatten soğutursa bil ki; şeytan içindedir.',
	'İnsanlardaki güzellik, altın yaldızdır.',
	'Eşeğin varsa mutlaka semer de olur. Canın var ise ekmek az çok gelir korkma.',
	'Tenini geliştirip de sonra ‘İnsanlar bana hased ediyor ‘diyen yanıldı. Hasedci içinde a ahmak!.',
	'Nefsini öldürürsen, özür dilemekten kurtulursun.',
	'Allah seni çirkin yaratmış olabilir. Bari ahlakını güzelleştir de hem yüzü hem huyu çirkin olmaktan kurtul.',
	'Bu dünyada en iyi ehliyet, iyi huydur.',
	'Fazileti ve mahareti kenara at. Hak yolda iyi huy ve hizmet fayda verir.',
	'Demirciler demir döverler. Demir kıpkırmızı olur da silah olur işe yarar. O demir, meşakkat çeken fakirdir.',
	'İnsan; dilinin altında gizlidir. Dil, can kapısına perdedir. Rüzgâr eserse perde açılır, içi görünür.',
	'Halk kendinden gafildir. Herkes önce kendi kusurunu görebilse ıslah edicilere ihtiyaç kalır mıydı? Kendi yüzünü görmek herkese nasip olmaz. Gören, Hak nurunu görür.',
	'Her şey, neye layıksa ona dönüşür.',
	'Her hünerin aslı, hayal ve düşüncedir.',
	'Kötü huylu güzel yüz, sahte paraya benzer.',
	'Sevgilinin huzurunda tedbir almayı bırak. Hoş,sana tedbir aldıran ya da aldırmayan da O zaten',
	'Şehadet mümine hayat, münafık için çürüme ve ölüm.',
	'Her canın gıdası farklıdır. Öküz şekerden ne anlar?',
	'İnsanın asıl gıdası Allah nurudur.',
	'Her şey bir şeyle buluşur da hayat bulur. Erkek kadınla buluşur çocuk olur, toprak bulutla buluşur bereket olur.',
	'Yeşilliğe bakanın gamı gider.',
	'Nice kişiler surette kaldı, özü göremedi. Göz aslında bir yağdır; gönülle birleşirse nur olur. Sen gözü gönülle destekle de nuru gör, sureti aş.',
	'Her kötü huyunu diken bil. Kaç kere ayağın yaralandı da fark etmiyorsun.',
	'Cömertlik; şehvet ve lezzetleri terk etmektir. Şehvet yüzünden düşen kalkamaz, hiç unutma.',
	'Heva ve hevesi bırakmak sağlam bir iptir. Buna tutunup arşa çıkarsın.',
	'His nuru insanı aşağı çeker, Hak nuru yukarı',
	'İhlasa eren kurtulur. Hiçbir ekmek tekrar buğday olmaz, hiçbir ayna tekrar teneke olmaz. Öyleyse ihlas makamına ermeye bakmak. Erdin mi geri inmezsin korkma.',
	'Güzele eş olan kurtuldu. Kara odun ateşe eş oldu aydınlık geldi. Ölmüş buğday (ekmek) cana eş oldu hayat geldi.',
	'Hıristiyanların cehaletine bak ki; asıldı dedikleri İsa ‘dan medet umarlar. Bizim İsa ‘mız diri.',
	'Haset, pusuya yatmış kurttur.',
	'Bedene hangi huy galip ise hüküm onundur. Maden içinde altın fazla ise altın sayılır, bakır fazla ise bakır sayılır. Sevabın fazla olsun ki; mümin diye hüküm verilsin.',
	'Öküz nefsini öldür de gizli ruh dirilsin.',
	'Zina edenler avret yerleri kokarak, şarap içenler ağızları kokarak haşrolacaklar.',
	'Dost, altın gibidir, bela da ateşe benzer. Halis altın ateş içinde saf hale gelir.',
	'Gaybı bilen Allah ‘ın has kulları kalb casusudur. Has bilgi almak istersen o casuslarla irtibata geç.',
	'Lokman iyi bir köle idi. Efendisi onda bereket sezdi de her yemeği önce ona verir sonra onun artığını yerdi. Bir gün karpuz aldı efendisi ve lokmana yollamadı, onu huzuruna çağırdı. ‘Lokman al karpuz ye ‘dedi bir dilim verdi. Lokman iştahla yedi. Bir daha kesti onu da yedi. Derken son dilime gelindi. Efendi ‘Bunu da ben yiyeyim ‘dedi. Isırması ile tükürmesi bir oldu. Efendi ‘Lokman bu karpuz zehir, nasıl yedin, niye demedin bize ? ‘dedi.',
	'Lokman ‘Efendim, bana bugüne değin öyle çok ihsan ettiniz ki, bu karpuz acı diyemezdim. Bu edebe ters olur, size nankörlük olurdu ‘dedi.',
	'Hak ‘tan gelen belaları acı karpuz bil. Sana ne nimetler verdi. Acı karpuz verdi diye hemen kızacak mısın, yoksa Lokman olma niyetin var mı?',
	'Sevgiden acılar tatlı, bakır altın olur. Sevgiden ölü dirilir. Sevgi, bilgi neticesidir. Noksan bilgi, aşk doğurmaz.',
	'Aklın özelliği sonu görmektir. Sonu görmeyen akıl ise nefsindir.',
	'Bir yandan korku, bir yandan ümidin varsa iki kanatlı olursun.Tek kanatlı uçulmaz zaten.',
	'Can İbrahim’i olursa onu ateş yakar mı?',
	'Hile eden, hile bulur.',
	'Allah hükmeder dilediğini yapar. Bazen derdin kendisi bile şifa olur.',
	'Tevbe de elde değildir. O nasip ederse tevbe edersin.',
	'Tevbe tohumunu gözyaşı ile sulamazsan rahmet meyvesi nasıl beklersin',
	'Akılsız dost, düşman demektir.',
	'Musa, dağda bir çobana uğradı. Çoban aklınca Allah ‘ı zikrediyordu. Şöyle diyordu:',
	'‘Hey koca Tanrı!.. Gel bana sakalını tarayayım, gel bitini ayıklayayım, gel sana süt içireyim, gel de kulübemde dinlen ‘',
	'Musa hiddetlendi:',
	'‘Behey sersem, Allah ‘la nasıl konuşursun? Dua ederken kâfir oldun gitti, behey akılsız ‘',
	'Çoban bir feryat etti ki, ağlayarak tası tarağı bıraktı çöllere düştü. Allah Musa ‘ya vahyetti;',
	'‘Kulumla arama girmeye utanmaz mısın? O ne güzel beni kendi aklı ve gönlünce anardı. Ey Musa sen Allah ‘a yaklaştırmaya mı geldin uzaklaştırmaya mı? ‘',
	'Musa hatasını anladı ve üzüldü de çobanın ardına düştü. Çoban çöllerde idi artık. Musa ‘Hakkını helal et, sürünün başına dön ‘dedi. Çoban ‘Sen beni azarlayana dek ben dünyada idim. Şimdi Rabbim beni öyle bir nurla ateşledi ki durmam artık, perde açıldı ey Musa! ‘dedi ve gözden kayboldu.',
	'Can, sevgiden nurdur. Allah can ehlinin diline bakmaz kalbine bakar. Kâbe ‘nin içine girene ‘Kıbleye dön ‘demek ne kadar abestir.',
	'Âşıkların şeriatı da mezhebi de Allah ‘tır.',
	'Ölümün sırrı haşrde, kanın sırrı bedende ortaya çıkar.',
	'Karalanmış tahtaya yazı yazılmaz. Bil ki, Allah ‘ın bela vermesi ve seni ağlatması rahmet yazısı yazmak için kalp tahtanı temizlemesi demektir.',
	'Kim altına ve gümüşe ermiş ise bil ki, kazanma zahmetine katlanmış demektir.',
	'Ay, ancak geceleyin cilve eder. Sevgiliye gece git.',
	'‘Akıllının düşmanlığı cahilin sevgisinden yeğdir ‘der Hak Peygamber.',
	'Adamın biri ağaç altında uyurken ağzına yılan girdi. Bunu uzaktan gören yiğit bir atlı koştu ve hemen uyuyan adamı uyandırıp kırbaçlamaya başladı ve ona yerden çürük elmaları yemesini emretti. Adam korkudan yedi. Sonra yiğit adamı kırbaçlayarak koşturuyordu. Zavallı adam çöllerde saatlerce koştu. Kan ter içinde kalmıştı. Nihayet yere diz çöktü ve başladı kusmaya. Yılan çıkıverdi. Adam yiğite minnetle baktı ve ‘A yiğidim bunu neden baştan demedin, sana düşman kesilmiştim şimdi minnettarım, canım kurtuldu . ‘dedi.',
	'Yiğit ‘Baştan desem ödün patlar yaşayamazdın. Kurtulman için kırbaç, çürük elma ve koşma gerekiyordu ‘dedi.',
	'İyi anla! Yılan giren adam sensin. Yiğit, Hak Nebi…Kırbaçlar dünyevi eza ve belalar. Çürük elma fakirliktir. İçinden çıkan yılan ise nefsin. Onu defetmeden kurtulamazsın.',
	'Gönül aynan saf olmadıkça çirkini güzelden ayıramazsın.',
	'Gülsuyuna b.k böcekleri üşüşmüş ise, bil ki o su aslını yitirmiştir.',
	'İblis Adem ‘e secde etmiş olsaydı; Adem, Adem olmazdı.',
	'Aptalın sevgisi, ayı sevgisidir. Kini sevgidir, sevgisi de kin.',
	'İhsan etmek kine merhemdir.',
	'Cemaate dost ol. Kervan kalabalık ise eşkıyanın cesareti kırılır.',
	'Miractan maksat, Dost ‘u görmek idi. Bu arada arş da görüldü melekler de.',
	'Gönül uykuda penceredir. Uyanık rüya görenler ise ariflerdir.',
	'Ağrı, sızı ve hastalık hazinedir. Deri yırtıldı mı iç tazelenir .',
	'Akıl, başka bir akılla kuvvet bulur.',
	'Dünyada üç tip kadın vardır, ikisi zahmet ve mihnet, biri hazinedir:',
	'1-Bakire olanı alırsan, her şeyi ile senindir, hazinedir.',
	'2-Dul olanı alırsan yarısı senindir, yarısı eski kocasının.',
	'3-Hem dul hem çocuklu alırsan hiç senin olmaz, aklı hep çocuğun babasındadır.',
	'Anaları ağrı tutmasa, çocuk doğmaz. Bu gönül gebedir, ağrısı bela. Nasihatler de ananın ebesi.',
	'Allah ‘ın feyzine geç mazhar oldu isen üzülme. Bil ki, O ihmal etmez, imhal eder (mühlet verir, zamanı vardır.)',
	'Vuslat muhabbeti duymak dilersen VEDDUHA suresini çok oku.',
	'Ateşe mensup nefsi gül bahçesi yap. Vefa tohumunu ek de zikir ve tesbih bülbülleri ötüşmeye başlasın.',
	'Kahırla lütuf birbirine eştir. İkisinden rahmet doğar.',
	'Sevdiğin şeyler, seni kör ve sağır eder.',
	'Gönül yalan sözden ferah bulmaz. Yağa su karışırsa kandil güzel aydınlatır mı?',
	'Halk, arzu ve heva sarhoşudur .',
	'Kasıtsız olmak bilgisizi âlim yapar, kasıt ve garez bilgiliyi zalim yapar.',
	'Avamın ibadeti havâsın günahıdır .',
	'Dostlarla olunca acı yemiş bile hoş olur.',
	'Yemin, yalancıların siperidir. Doğrular buna ihtiyaç duymaz ki.',
	'Hak olmadıkça batıl anlaşılmaz.',
	'Allah Kadir gecesinde gizlidir.',
	'Korku, açlık, mal azlığı ve hastalık can hazinesinin ortaya çıkması içindir.',
	'Söz manaya yetmez. Söz hesaba benzer. Hesap güneşe bizi ne kadar yaklaştırır ki? Allah ‘ı bilenin dili kapanır, gönlü manaya açılır .',
	'Oltadaki et, balığın canını almak içindir. Onu ihsan sanan helak oldu',
	'Başkasının ayıbını söyleyen, onu mutlaka görecek demektir .',
	'İnsanın yarısı ayıp, yarısı gaybtır.',
	'Allah merhamet etti de bize Nuh ve Hud kavminin helâkini örnek yaptı. Biz ibret alalım diye onları kahretti. Ya tersini yapsaydı?',
	'Ekmeğim yok diye ağlayan! Mademki Allah merhametli diye inandın, korku niye?',
	'Yunus balık karnında pişti.Yunus tesbihle karaya çıktı. Sabretmek canın tesbihidir. Sabır sırattır, geçerken sızlanma, nasıl olsa yolun cennete çıkacak.',
	'Dünya hikmeti zannı ve şüpheyi artırır, din hikmeti kişiyi arşa çıkarır.',
	'Ahir zamanın adi ukalaları kendilerini evvelki alimlerden üstün görür .',
	'Fikir ona derler ki; bir yol açsın. Yol ona derler ki; Allah ‘a varsın.',
	'Duygu koyunlarını Allah yaylasında otlat ki, hakikât bahçesine gidebilesin .',
	'Söz yuva gibidir, Manâ kuş gibi. Cisim ırmaktır, ruh su gibi.',
	'Nefs Nemruttur. Ateş yakar onu. İbrahim nefsi öldürdü ateş yakmadı.',
	'Kılavuz yolcuya gerek, menzile varana kılavuz gerekmez.',
	'Her şey zıddı ile anlaşılır .',
	'Karalanmış kağıtta yazı okunmaz, beyaz kağıtta okunur. İçini arıt da nur görülsün.',
	'İçsiz tohum fidan olmaz, zevksiz ibadet fayda etmez .',
	'Güneş ışığı pisliğe düşmekle değerini yitirmez.',
	'Kibir ve kinin başlangıcı şehvettir .',
	'Büyüklenmek zehirdir.',
	'Şehvet yılanını hemen ez ki, büyüyüp başına ejderha kesilmesin.',
	'Yoldaşını çok övme, ayrılık gelir.',
	'Anne yavrusuna süt vermek için çocuğu çağırsa çocuk delil ister mi, güvenerek hemen koşar. Peygamber anadır, hâlâ sözlerinde delil ve mantık mı ararsın?',
	'Kıssa ölçektir, mana içindeki buğday. Akıllı olan, taneyi alır ölçeği almaz, ona takılmaz.',
	'Aralarında sözden eser yok, ama Bülbülle Gülden ne maceralar dinlersin ibret alırsın!.',
	'Gönlü açık olanın, eli de açık olur.',
	'Sirkeyi ısıtsan bal olmaz, balı ısıtsan sirke olmaz.',
	'Uzağa bakış kör eder. Adam sarayda uyur, sarayı görmez. Yakına bak da gör kendindekini. Gök gürlemesi, susuzun başını ağrıtır. Bilmez ki rahmet gelecek.',
	'Kötü zan, insana güçlü bir engeldir.',
	'Her mizacın mayası, anasıdır.',
	'Âlemde her şey bir şeyi yemektedir. Âlem adeta, yenen ve yiyenden ibarettir.',
	'Toprak yağmuru yer, meyveler yetişir; insan meyveleri yer de can hayat bulur. Fakat yeni bir can ve bakışa sahip olmak için bazı yemeleri terk etmen gerekir.',
	'Bebek memeyi ve sütü bırakırsa önüne meyveler ve enva-i çeşit yemeklerden oluşan bir sofra açarlar. Sen de lokma yemeyi azalt da can sofrana farklı bir âlemden taamlar açılsın.',
	'Âlemin sonu yoktur ,âleme aşık olanların da… O âlem ehli ise ebedidir ve hep bir aradadır.',
	'Tamah, kulağa bir şey duyurmaz. Garez, göze perde olur.',
	'Âleme tamah edersen, öte âlemi duyacak ne kulağın, ne de görecek gözün olur..',
	'Avcılar ormanda yol alırken taze ve körpe bir fil yavrusunu vurup yediler. Fil geldi onlar uyurken ağızlarını kokladı da yavrusunu yiyen iki avcıyı öldürdü.Birini öldürmedi. ',
	'Dikkat et veliler Allah ‘ın çocukları gibidir. Aleyhlerine olur ve konuşursan gıybetin leş kokusu ta Allah ‘a gider de başına gadab-ı ilahi gelir.',
	'Peygamber, baştan başa kulaktır, gözdür.',
	'Ömrün, altın kesesine benzer; gece-gündüz de para sayan adama.',
	'Eski ve tecrübe görmüş akıl;sana yeni bir baht bağışlar.',
	'Kibir-hırs ve şehvet kokusu, söz söylerken ağzında soğan gibi kokar. O koku yüzünden duan reddedilir. O kalp, o koku ile içini dışına vurur.',
	'Sözün eğri özün doğru olursa, o söz eğriliği Allah ‘a makbuldur.',
	'Eğer duada güzel bir nefese sahip değilsen, var yürü de hoş nefesli bir dosttan dua iste.',
	'Allah adı temizdir.Temizlik gelince pislik pılını pırtısını toplar gider.Gün parladı mı gece kaçar. Allah adını ağzına al da gamın ve kederin kaçıp gitsin.',
	'Yalvaranın ‘Allah ‘ demesi Allah ‘ın ‘ buyur kulum ‘ demesidir .',
	'Kötü yaratılışlı kişi Allah ‘a yalvaramasın diye Allah ona dert keder vermez. Unutma, Firavun ‘un başı bir kez bile ağrımadı.',
	'Dert; Allah ‘ı gizlice anmana vesile olacaksa tüm dünya malından yeğdir. Dertsiz dua soğuktur. Dertli dua gönülden, aşktan gelir.',
	'Sabır;sıkıntıların anahtarıdır.',
	'Pusudan sabır ve ihtiyat etmeksizin kurtulamazsın. Sabır, ihtiyatın eli ayağıdır.',
	'İhtiyatsızlık, tedbirsizlik; pişmanlıktır .',
	'İyilik ettiğin kişinin şerrinden sakın.',
	'Sohbet var; keskin kılıca benzer, bostanı, ekini kış gibi keser biçer. Sohbet var; ilkbahar gibidir, her tarafı yapar, sayısız meyveler bitirir.',
	'Tedbir ve ihtiyat bastonun yoksa, bari gözü gören birine tutun.',
	'İsa Nebi ‘nin ibadet yeri, gönül ehlinin sofrasıdır.',
	'Hırsız mal çaldı mı içini bir sıkıntı kaplar. Bu mazlumun ahının tesiridir.',
	'İnsan yazın kışı ister, kışın da yazı… Bir hale katiyen razı olmaz,ne darlıktan hoşlanır, ne genişlikten ve boşluktan. Rahata erdi mi de inkâra sapar. Geberesi insan, efendisine ne kadar da nankördür.',
	'Seni dostundan ayıran sözü dinleme.',
	'Gökten yeryüzüne ne yağarsa yer ne kaçabilir, ne de çare bulabilir. ‘Sizi topraktan yarattık ‘ayetini unutur da Hak ‘tan gelene öfkelenirsin. Topraksın, arştan gelenden kaçamazsın. Toprak gibi razı ve mütevazı ol.',
	'Kaza ve kader felekten baş çıkardı mı, akıllıların hepsi kör, sağır olur.',
	'Kaza ve kaderden, yine kaza ve kadere kaçan kurtulur.',
	'Bir dertlinin dert ve elemini dinlemek ona verilecek en büyük zekâttır.',
	'Dertli kişinin tereddüt ve elemle dolu gönül evi vardır. Onu dinlemek, o eve pencere açıp havalandırmak demektir.',
	'Tereddüt, hapis ve zindandır. Ruhu çeker de bir yana yönelmesine engel olur.',
	'Gamdan sevinmeye çalış. Gam, vuslat tuzağıdır. Bu yolda aşağıya düşüş aslında hakikâte yükseliştir. Gam bir hazinedir. Senin zahmet ve meşakkât çekişinse maden… Gam derdine düşen, madeni kazmaya başlamıştır. Azimle kazan, ulaşır defineye.',
	'Dostlar!.. Gönül, eminlik ve huzurdur.',
	'Acı; tatlı dudakların tesiri ile tatlılaşır. Diken, gül bahçesi nedeni ile gönül çeker hale gelir.',
	'Suretten geçerseniz, her şeyde sevgiliyi görürsünüz. Mecnun bir köpeğe iltifat ediyordu.Halk onu kınadı.Mecnun ’siz anlayamazsınız bu, Leyla ‘nın semtinin köpeğidir,onda ben sevgilimi gördüm ‘dedi.',
	'Kılavuzsuz yola gidene iki günlük mesafe yüz yıl olur.',
	'Hırs sahibi, mahrumdur.',
	'Boğaz nimet yerse, yüz utanır.',
	'Dosttan gelen bir cefa; yabancının üç yüz bin cefasından daha ağırdır.',
	'İnsanların uğradıkları bela ve mihnet, dikkâtli bakarsan alışmadıkları şeyden meydana gelir.',
	'Temiz kişilerin toprağını öpmek; aşağılıkların taht ve bahçesine oturmaktan iyidir. Gönlü aydın bir ere kul olmak, Padişahın başında tac olmaktan yeğdir.',
	'Doğruluk ve yanıp yıkılmışlık Veli âdetidir. Utanmazlık da her aşağılık kişinin sığındığı bir sanattır.',
	'İmtihan içinde imtihan vardır. Derlen toplan da ufak bir imtihanda satma kendini.',
	'Ya doğru ol, doğruluğunu göster; yahut sus da merhamete eriş, sonra coş.',
	'Allah ‘beni çağırdın mı suçlu da olsan, putperest de olsan icabet ederim. Onun için duadan hiç çekinme, hiç usanma, dua nihayet seni nefsinden kurtarır ‘demiştir.',
	'Mal yılandır, onda ne zehirler var.',
	'Tatlı suyu tatmadıkça, acı su insanın gözünde nur gibi görünür.',
	'Allah ‘Allah ‘ın inayetine erenler, yeryüzünde yavaş ve mülayim yürürler ‘ buyurdu.',
	'İnsan, kendine yasaklanan şeye karşı hırslıdır.',
	'İnciler deniz dibinde taşlarla karışık dururlar. Övülecek şeyler, ayıplar arasındadır.',
	'Takdirle savaşa girişen, ona baskın yapmaya kalkışan baş aşağı gelir, kendi kanına bulanır.Yer göğe düşmanlık etmeye kalkışırsa, çorak kalmaya mahkûmdur.',
	'Arayan; ister yavaş gitsin ister hızlı, aradığına mutlaka ulaşır.',
	'İnsan rahat ve geçim için yılanlar arar durur.Gamdan kurtulmak için gam yer durur.',
	'İnsan duygudan çıkmadıkça, gayb âlemine tamamen yabancıdır.',
	'Nefsin ejderhadır. Öldü sanma, uykuya dalar o. Dertten eline fırsat düşmediği için uyur. Derdin bitince çıkar hemen. Hüner; dertsizken de nefsi uykuda tutmadadır.',
	'Nefsi uykudan şehvet güneşi uyandırır. Yüzünü ört onun da, şehvet güneşi onu uyandırmasın.',
	'Sıkıntıdan kurtuluşa giden gizli yol, o sıkıntının içindedir.',
	'Hüner ve marifette ileride olanlar, manâca geridedirler.',
	'Ad-san sahibi olmazsan, insanlar arasında kaybolurum sanma. Defineyi açık ve meşhur yere koymazlar.',
	'Şehirlerde ad ve san sahibi olmazsan Allah kullarının halini daha iyi bilirsin.',
	'Geçmiş ve gelecek insana göredir. Yoksa hakikat âlemi birdir.',
	'Akılla hüneri sat da, hayran olmayı satın al.',
	'Süt emen bebek sütten kesilince yer gıdası almaya başlar.Sen de yerin gıdalarından kesil de arştan gelen kalp gıdalarını almaya başla.',
	'Gönül ehli değilsen uyanık ol da bir gönül iste. Mücadeleye başla.',
	'İnsan önce bir kadını sever. Ama vuslata erince kadın gözünde basitleşir. Vuslat; kadını yaratan Allah ‘a varmaktır.',
	'Allah hükmüne âşık olan nurlanır, yaratıklara âşık olan ise kâfir olur.',
	'Dudak kuruluğu suyu haber verir. Bu eziyet ve susuzluk; suya vuslatın alametidir. Bu aramak; kutlu bir iştir. Hak yolundaki bu isteğin engellerini giderir. İstek; dileklerin anahtarıdır.',
	'Padişah tarafından kabul edildikten sonra, ona mektup yazmak, elçi koymak ayıptır. Huzura kabul edilmeye bak.',
	'İnsan cansız şeylerin Allah ‘ı zikrini inkâr eder. Ateş canlı bir kul olmasa İbrahim ‘i yakmayacağını nasıl bilebilirdi? Ateş itaat etti Rabbine de yakmadı Halil ‘i.',
	'Allah ‘ım bana zahmetsiz, eziyetsiz rızık ver demek günah değildir. Sen de öyle de.Davut (as) döneminde böyle diyen adam nice lütuflara mazhar oldu.',
	'Cüzi aklın afeti vehim ve zandır. Zan ve vehmin vatanı karanlıklardır.',
	'Bilginin iki kanadı vardır, şüphenin tek. Şüphe ve zan sahibi, hiçbir zaman uçamaz.',
	'İnsan bir işe ciddiyetle koyuldu mu hastalığı görmez, gözleri dış âleme kör olur.',
	'Kötüye yormak ve vehim yapmak insanı derdi yokken bile hasta eder.Onun için olaylara iyi bak.',
	'Ten elbiseye benzer. Elbiseye yapışıp durma, koş da diken ustayı ara.',
	'Herkes bir iş için yetiştirilmiş, gönlüne o işin meyli verilmiştir.',
	'Kendinde göklere doğru bir meyil sezersen hemen kanat aç.',
	'Akıllılar; olayların başında feryat eder, bilgisizlerse işin sonunda başlarını yere vururlar.',
	'Bu âlem bir rüyadır. Zanna kapılma,rüyada elin kesilse de korkma elin yerindedir. (Dünya bir rüya ise, başına gelen felaketler de geçicidir.Neden çok üzülürsün ki?)',
	'Uykuda aklın gider, ama uyanınca sana yine gelir o. Ahirette de aklın, duygun tam olacaktır. Lezzetleri oraya sakla.',
	'Seni köpek ısırsa hemen hayvanı döver ya da küfredersin. Velilerden birini ısırsa onlar şöyle derler: ‘Allah ‘ım başka kullarını ısırmasın bu hayvan. Sen onun hırsını al ‘.',
	'Halk rahmetin pek azına mazhar olur. Himmet sahipleri ise çoğuna.',
	'Gözyaşları merhamete delildir.Yürek yanmasa göz ağlamaz.',
	'Ağlayış ya elemden olur, ya ayrılıktan.',
	'Duygu akla esirdir. Akıl da ruhun esiridir.',
	'Sabır; genişliğin anahtarıdır.',
	'‘Velasri Suresi ‘nin sonunu dikkâtlice oku. Allah o surede sabrı Hak ile beraber andı. Sabr, Hakk ‘a eştir.',
	'Allah ne alırsa ona karşılık ihsanda bulunur. Bunun için Veliler kaybettiklerine üzülmez ve Allah ‘a itiraz etmezler.',
	'Parça bütünden koptu mu işe yaramaz. Bedenden bir uzuv kesilirse o uzuv işe yaramaz hatta murdar olur. Tekrar aslına iade edilmezse ölü kalır. Hak ‘tan nasıl ayrı kalabilirsin?Sen oraya aitsin.',
	'Baş köşelere hevesi bırak. Senin baş köşen Hakk ‘ın yoluna revan olmaktır.',
	'Âşık, gönül yurduna sefer eden kişidir.',
	'Zamana bağlı olan, zamansızlığı kavrayamaz. Onu kavramak için hayret etmeyi öğren.',
	'Anlayış sudur, beden testi. Testi kırılınca içindeki su dökülür gider.',
	'İftitah tekbirinin manâsı şudur:',
	'Allah ‘ım biz senin huzurunda kurbanız.',
	'Koyun keserken ‘Allahu Ekber ‘deriz. ‘Allah büyüktür ‘der de hayvanı keseriz. Namaza başlarken ‘Allahuekber ‘demekle şunu demek istiyorsun:',
	'Allah ‘ım hayvan olan nefsimi isminle kesiyorum.',
	'Hileler ve hesaplar öldü mü Dua zamanı gelir.',
	'İhtiyat nedir? Her an gelebilecek belayı görmek.',
	'Gönle gelen her ferah, bir sıkıntı sonucudur.',
	'Kese ve dağarcığın değeri altına bağlıdır. İçinde altın olmasa beş para etmezler.',
	'Allah kimi gönül makamına çekerse, o kişide ten cinsiyeti kalmaz.',
	'Apaydın gündüz vakti bir kişi mum ararsa bu, onun körlüğüne delalet eder. (İslam gelmiş, hâlâ yollar ararsın)',
	'Sabır ve sukut, Allah rahmetine sebep olur.',
	'Ey edepli kişi!',
	'Derdin tazelensin istemiyorsan, bu doktorun önünde soru sormayı bırak da başını yere koy.(Allah ‘a secde et)',
	'Yazı yazanın elindeki kâlem gibi göz ve gönül Allah ‘ın iki parmağı arasındadır.',
	'Kel olanlar saç hakkında konuşamazlar. Sırlara ermemişsen o âlemin edebiyatını yapma, gülünç olursun.',
	'Davud (as ) ‘ın sesini dağlar duydu da zikre katıldı, ama kâfir yürekler duymadı.',
	'Dünya; kuşa tane saçan avcıya benzer.Tanelere koşarsan karnın azıcık doyar, sonu tuzaktır. Tembellik etme, taneyi bırak da ovaya Hakk ‘ın rahmet vadisine uçmaya bak.',
	'Nimete şükür; nimetten daha tatlıdır.',
	'Şükür, nimetin canıdır. Nimet deriye benzer. Seni sevgiliye ulaştıracak olan candır.Nimet insana gaflet verir, şükür ise uyandırır. Şükür nimeti, gözünü doyurur,seni bey yapar.Allah sofrasından yersen, oburluğun ve nimet hırsın kalmaz.',
	'Karanlığın ardında nice güneşler var. Ümitsizlikten sonra nice ümitler var!…',
	'Sabırla nefsin belini kır. O alçaktır, iyilik etmeye hiç gelmez.',
	'Alçaklar cefa ve derde düşünce arınır, temizlenirler. Vefa gördüler mi hemen cefa etmeye başlarlar.',
	'Zindan alçak ve hırsızların ibadet yeridir. Orada Hak akıllarına gelir.',
	'Kitaptan amaç, içindekinden yararlanılmasıdır. Ama sen dilersen kitabı yastık da yaparsın. Bu sana bağlı.',
	'Alçak nefse iyilik etme. Kötü davran da alçaklar gibi sana eğilsin, teslim olsun.',
	'Şükür; sıkıntı ve dertten gelişir.',
	'Aşkın gıdası, ekmeksiz ekmeğe âşık olmaktır. Aşkında doğru olan kişi, varlığa bağlanamaz. Âşıkların varlıkla işi olmaz. Onlar, sermayesiz kâr elde edenlerdir.',
	'Yüzünü yıkamayan, huri yüzü göremez.(Abdest)',
	'Canların gıdası, aşktır. Ruhun gıdası da açlık.',
	'İlim sevgilisi olmak ile âlim olmak farklıdır. Nice âlimler sadece bilgi hamalı oldular. Sen ilim sevgilisi olmaya bak.',
	'Kendini unutursan, seni anarlar. Kul olursan, azat ederler.',
	'Halkın işi kaza ve kaderledir.Midenin hararet ve kuvveti olmasa diş keskin olmaz.',
	'Kim yanmayı başarmışsa nuru o bulur.',
	'Allah, bunalan kişinin duasını kabul eder. Meryem iffetinden ‘beni fahişe sanırlar ‘diye bunaldı, Hakk ‘a yalvardı da Allah İsa ‘yı konuşturdu.',
	'Dert nerede ise deva oraya gider.Yoksulluk nerede ise nimet oraya gider.Soru nerede ise cevap oraya verilir.Gemi nerede ise su oradadır.Suyu ara, susuzluğu elde et de sular alttan da yerden de fışkırmaya başlasın.',
	'Yavrunun boğazı nazik yaratıldığı için Allah sütü kolay akıttı. Nazik ol, nazenin ol, fakir ol ki, nimet aksın sana.',
	'Birini Allah överse canlı cansız her şey onu över.Kimi Allah koruyor ise onu yolda kuşlar ve kurtlar da korur.',
	'Nurlu kişiden yansıyan da nurdur.Karanlıkta kalandan zaten yansıma olmaz ki.',
	'Kötü bir işe düşünce ibret al, üzüntüye düşme. Fayda ve zarar zamanında da gülmeye bak.Gülün yapraklarını tek tek koparsan da sana gülümser o.Bir dikenden niye gama düşersin? Diken olmasa gül olur mu?',
	'Tasavvuf; sıkıntı anında dahi neşeli olmanın adıdır.',
	'İbret almayı Allah ‘tan iste. Kitap ve harflerden değil.',
	'Kâr beklemeksizin veren, sadece Allah ‘tır.',
	'Bedenin halvette eziyet çekmesi ruha dirilik verir.',
	'Dudağını yumup sırrı gizleyebilirsen gayb sırrını öğrenebilirsin.',
	'Beden ve mal ziyanı, ruha faydalıdır.',
	'İnsan, gaybı gören göze sahip olmadıkça insan olamaz.',
	'Her meyvenin içi, kabuğundan tatlıdır. Ten kabuk, ruh içtir.',
	'Sana bir yerden bir töhmet gelmiş ise bil ki; zulmettiğin biri sıkıntıya düşmüş,sana beddua etmiştir.',
	'Mazluma zulmetmen, tohum ekmendir. Unutma, o tohum zakkum olur ve zehirler seni.',
	'Aklını başına al, ateşi ancak din nuru söndürür.',
	'Yavaş iş Rahman’dandır; acele ve telaş ise şeytandan. Unutma, Allah yer ve gökleri altı günde yarattı.',
	'Yüzü kara olanlar, hakikâti görmeyenlerdir. Sen Bilali Habeşi ‘nin kara yüzüne hayran ol. Kişinin adı Ebu Cehil ’se yüzü beyaz olsa neye yarar ki?',
	'Kalbi ölen kişiye dünya geniş görünür.',
	'Ana ağrı çekmese doğum olur mu? Sıkıntı çekeceksin ki, sırlar âlemine doğasın.',
	'Gaflet, tenden ileri gelir.Ten öldü mü şüphe de kalmaz gaflet de.',
	'Daima suda kalmak, balığın harcıdır. Yılan nerede suda kalacak?',
	'Geceyi yaratmasaydı Allah, bu millet kazanma hırsından kendini helak ederdi. Sıkıntılar gecedir. Dinlen, kederlenme. Sabah elbet olacak.',
	'Kışın yüzü soğuktur ama şefkâtlidir. Yaz gülümser ama yakar, kavurur. Darlık geldi mi onda genişlik görmeye bak.',
	'Allah ‘ın esas rızkı hikmettir. Onu yemek için bu ağzını kapat da gönül ağzını aç.',
	'Tanımamaktan beter hastalık yoktur. Sevgili (Allah) şahdamarından daha yakın, ama haberin yok.',
	'Bir yerde dert ve aşk artarsa orada ne Ebu Hanife der verebilir ne de Şafii. O kişi, kendinin hocasıdır artık.',
	'Âşıklara dostun güzel yüzü, en iyi öğretmendir.',
	'Aşk davadır,cefa çekmek Şahid. Şahidsiz dava kazanılır mı?',
	'Sopayla kilime vuranın gayesi, kilimi dövmek değil, tozu kovmaktır. Allah tozunu alıyor, niye kederlenirsin?',
	'Nefsle şeytan ikisi de birdir, ama iki gibi görünür. Akılla melek de birdir.',
	'Malla beden eriyen kar gibidir. Ama onları satmak dilersen, en iyi alıcı Allah ‘tır.',
	'Koyunlar sayamayacak kadar çok olsa da kasap bundan korkar mı?',
	'Varılan yerin tatlılığı, ona ulaşmak için yolda çekilen sıkıntıların fazlalığı ile ölçülür.',
	'Ne kadar gurbet çekersen, akraban ve vatanın o kadar sana tatlı olur.',
	'Belaya uğrayan müminin misali, tencerede kaynayan nohuta benzer. Nohut, yanmaktan ıstırap duyar da kaçmak için kapağı zorlar. Hanım, çıkmasın diye kepçe ile bastırır. Nohut yanmanın yok oluş değil nimete dönüşme olduğunu bilse kaçar mıydı? Allah pişesin, olgun olasın diye seni belalarla kaynatır.',
	'Allah ‘ın rahmeti kahrından ileridir. Kahırlara eseflenme, mutlaka rahmet o kahrı kuşatacaktır.',
	'Nur gönülden doğar da göze vurur. Gönül olmasa, göz bir şey görmez.',
	'Kıyamet, bize bayramdır.',
	'Her âşık sevgilisine kavuşmayı özler. Sevgili de hep O ‘nu aramaktadır. Aşk âşıkları zayıflatır, sevgililerin vücudu ise aşkla güzelleşir. Gönlünde Allah sevgisi arttı mı, bil ki Allah da seni sevmektedir.',
	'Susuzluk; suyun çekmesinden ileri gelir.',
	'Âlem adeta erkek ve dişidir. Yer kadın gibidir, ana gibi yetiştirir meyve ve nebatatı. Gök, erkek gibi taşır eve gerekli olanları. Allah, evlatlar yetişsin diye erkekle kadını birbirine meyilli yarattı. Gece gündüze sarılır da gün doğar. Her şey, bir şeyin parçasıdır ve parçalar bütünü çeker de kâinatta devran döner.',
	'Ten yeşilliğe ve akarsuya meyleder. Çünkü aslı topraktır. Can hikmete ve bilgilere meyleder. Ten yere, Can göklere meyleder. Ruhun aslı yücelerdendir, tenin aslı yerden.',
	'Kim bir şey isterse, istediği şey de ona rağbet eder.',
	'Müminlerin nişanı kırık ve mağlup olmalarıdır. Ama o kırıklıkta bir güzellik var. Misk şişesi kırılırsa ortalığı güzel koku kaplar. Eşek tezeğini kırsan, burnunu tutarsın.',
	'Yusuf ‘un gömleğini alıp götüren hiçbir şey hissetmedi. Ama Yakup onda Yusuf ‘un kokusunu aldı. Şeytanlar levhi mahfuzun etrafını gezerler de zerre miktarı koku alamazlar.',
	'Helva kime nasipse o yer, parmağı uzun olan değil.',
	'Adamlık üzümde şarabı, yokta varı görmektir.',
	'Aşk öyle bir fazilettir ki; insanı faziletler sahibi yapar.',
	'Namahrem olanlar sevgiliyi göremezler. Dostun yüzünü onun civarında olan can görür.',
	'Hakikât şarabı aşkla kaynar.',
	'Nice güzel sözlüler var ki susmaktadırlar. Nice tatlı özlüler var ki; ekşi yüzlüdür. Mezarlığa var da bir bak; ne hatipler var ki susmuşlar, ne can yakan güzeller var ki, ekşimişler, toprak olmuşlar.',
	'Allah ‘ın gölgesi, kulun hemen başının üzerindedir.',
	'Peygamber dedi ki: Bir kapıyı sürekli çalarsanız mutlaka ses verilir, baş görülür. (O kapıyı dua ve zikirle çal.)',
	'Ayağın kırıldı diye üzülme. Allah sana belki kanat verecek. Kuyu dibinde kaldın diye kırılma, belki oradan bile bir kapı açılır. (Yusuf kuyudan sultan oldu)',
	'Hac Allah evini ziyarettir. Ev sahibini ziyaret ise erlik ister.',
	'Güneş, malı güzel gösterir diye, pazarları gündüz kurarlar.',
	'Mesnevi masal diyenlere göre masaldır. Kendini bu kitapta görmek ve anlamak ise erliktir.',
	'Dünyada mutlak kötü yoktur. Kötü, iyiye kıyasla kötüdür.',
	'Kim kendini Allah ‘a verirse, Allah da kendini ona verir.',
	'Kin; sapıklığın ve kâfirliğin temelidir.',
	'Akıllılar; parçada bütünü görenlerdir.',
	'Kötülük yaptın mı kork, çünkü o bir tohumdur, Allah yeşertir karşına çıkartır.',
	'Cennet aletle yapılmadı. Orayı inşa eden, amel ve niyetlerdir.',
	'Gönül evine bak. Gamla tozlandı mı tevbe süpürgesi ile süpür.',
	'Kendine gel. Sakın arşın nurundan ümit kesme.',
	'Miraç edenlerin yanında dur. Yokluk seni burak gibi göklere çıkarsın.',
	'Mal mülk, altın, cana yoldaş olmaz. Sen altın ver, sürme al da gözün açılsın.',
	'Biz hepimiz Adem ‘den parça idik. Cennette o ebedi nağmeleri duyduk, dinledik. Güzel sesi kuş sesini sevmemiz o ebedi sese hasretimizdendir.',
	'Edep; edepsizlerin edepsizliğine sabretmektir.',
	'Şikâyetçi kötü huyludur. İyi huylu şikâyet etmez. Tahammül eder.',
	'Şehvet pak kişilere köle olur. Çünkü halis altını ateş yakmaz.',
	'Muhammed halkın gözü önünde idi, ama manâsı gizli idi. Halkın çoğu sakal ve hırkaya takıldı. Manâyı göremedi.',
	'Aklın varsa, başka bir akılla dost ol.',
	'Lakap ve unvandan kaç, manâya yürü.',
	'Kargaya benzer nefsine uyma, o seni çöplüğe götürür.',
	'Gönlün bitkisi fikirdir. Fikir, kalpteki sırrı açık eder.',
	'İyiyi bilmedikçe kötüyü bilemezsin. Zıt, zıttı ile anlaşabilir.',
	'Bedenin secdegâhı olan mescit gönüldür. Kötü dost, insanın mescidinde biten keçi boynuzudur.',
	'Akıl ve zekâ taslamak şeytandan, aşk Adem ‘dendir.',
	'Aklı ve zekâyı sat da hayranlığı satın al. Akıl ve zekâ şüphedir. Hayranlık, bakış ve görüştür. Aklı Muhammed ‘e kurban et de ‘Allah bana yeter’de.',
	'Aklı dost aşkında kurban et.',
	'Kötü huyluya ilim öğretmek, eşkıyaya silah vermektir. Savaş ve cihad, eşkıyanın elinden silahı almak için farz olundu.',
	'Bilgi ve cömertlikten yaratılanlar meleklerdir. Bilgisiz cömertler bitki ve hayvanlardır. Yarı melek yarı hayvan olan ise Adem ‘dir.',
	'Can yücelere kanat açmak istedikçe, beden tırnakları ile yere sarılır, onu salmak istemez.',
	'Halkın çoğu fihristte kaldı. Kitabı okuyamadı. Sen kitabı okumaya bak.',
	'Gümüş bedenli güzellerin vücuduna aldanma. Bir de onları nine olunca gör.',
	'Seven kişi sevgilinin aleyhine sözlere sağır olur.',
	'Her şey bir şeyi çeker. Küfür kâfiri, doğruluk doğru yola gitmek isteyeni çeker.',
	'Şirinliklere mihenk taşı ölümdür.',
	'Elinde ışık varsa izi bulursun.',
	'Hırs ve tamah insanı kör eder.',
	'Balığı oltaya götüren, pisboğazlığıdır.',
	'Ağzından soğan kokusu gelmekte, sen misk anlatmaktasın (yaşamadan ahkâm kesme) .',
	'Merhamet, gönlü kırıkların, acizlerin nasibidir .',
	'Gökler ve yeri elma farzet ki, Allah ‘ın kudret ağacından yetişir.Sen elmanın içindeki kurt gibisin.Ne ağaçtan haberin var, ne bahçıvandan. Elmayı del çık da etrafına bak.',
	'Nur, gözsüz de görür.',
	'Sana dert gelirse başkasına kabahat yükleme.Kendine bak.',
	'Ahmak ağzıma helva tıksa hasta olurum. Akıllı kimse sövse şifa bulurum.',
	'Çeşmeyi gönlünde ara. Bir şeyi bulunmadığı yerde aramak, aramamaktır.',
	'Akıl, nefse kelepçedir.',
	'Belaların çoğu Peygamberlere gelir. En büyük bela, ham kişileri adam etmektir.',
	'Nur, gizlidir. Aramak ve sormak onun anahtarı.',
	'Azıksızlık azığı; her şeyden vazgeçiş, ariflik işaretidir.',
	'Sukut denizdir, söylemek ırmak.',
	'Akıl Allah ‘ın gölgesidir. Allah güneş, gölge güneşe karşı durabilir mi?',
	'Kendinden geçen kurtulur.',
	'Ansızın gelen her bela, neşe damının korkulu kenarında gelip çatmıştır.',
	'İhtiyarlık akıl ihtiyarlığıdır. Saç sakal ağarmakla adam olunmaz.',
	'Geçmişe acınmak hatadır.',
	'Ölmeden önce ölen, azaptan kurtulur.',
	'Akıl, şehvetin zıddıdır.',
	'Yapılmak için, yıkılmak gerek.',
	'Hilekârların işini işlersen iyi kişiler hakkında şüpheye düşersin.',
	'Sen temizlendin mi perde açılır. Pak kişilerin ruhu sana dönmeye başlar.',
	'Beden çevresinden kurtulunca, kulağında burnunda göz olur.',
	'Akıl cilası, heva ve heves kapanınca parlar.',
	'İyi su satmayan kör kuş, acı suyu Kevser zanneder.',
	'Sen fanisin.Varlığını Allah ‘a adarsan baki olursun.',
	'Her cins kendi cinsini çeker. İsa ve İdris melek cinsindendir. Onun için gökte yaşarlar. Kâfirler, şeytan ve ateş cinsindendir. Onun için cehenneme giderler.',
	'İsa, Allah sarhoşudur. Eşek, arpa sarhoşudur.',
	'Peygamberler ruh ve melek cinsindendir. Onun için melekleri çeker, vahiy alırlar.',
	'Hızır, Musa ile bindiği gemiyi deldi. Kurtuldular. Madem ki kırık olan kurtulur, kırıl yoksul ol; emniyet, yoksulluktadır.',
	'Üstünün dostu ol ki, üstün olasın.',
	'Hiçbir testici su konmasın diye, testi yapmaz. Âlemi boşa mı yaratıldı sanırsın.',
	'Gönlünün aydınlığı ve cilası nispetinde sırları görürsün.',
	'Talihsize zahmet gelir Pırtısını toplar, isyan ve küfür mahallesine gider. Talihliye zahmet gelir o da Allah ‘ın semtine koşar.',
	'Harfsiz ve sessiz konuşmak için ruhun bela çekmesi, anlayışlı olması gerektir.',
	'Soru da bilgiden doğar cevap da. Diken de topraktan biter, Gül de…',
	'Uykumuz ölümün kardeşidir. Bu kardeşe bak da ötekini tanı.',
	'Temiz kişiye ‘yoksul ‘demek hatadır. Çünkü, kalbi zengindir, o da Allah vergisidir.',
	'Kanaattan meydana gelen darlık, takvadandır.',
	'Kim din derdine düşerse, Allah öteki dertlerini alır .',
	'Dini avlamaya bak ki, onunla birlikte mal, mülk, güzellik ve sana fayda veren baht da sana gelsin. Bil ki ahiret deve kervanı, dünya da deve tüyüdür. Katara sahip olursan yün de deve de mal da sana gelir. Yünü alırsan deve senin olur mu?',
	'Ahmaklara verilecek cevap, susmaktır.',
	'Her fuzuli kişi Allah ‘ın lütfuna erseydi, Peygamber yolla maya gerek kalır mıydı?',
	'Akıl, şimşek ve aydınlık gibidir. Şimşeğin geçici ışığı vahyi anlamaya yetmez.',
	'Ulu akıl olan Allah ‘ın sözünü okumaktan amaç, kendini usanç ve elemden kurtarmaktır. Vesvese ve dert, bu sözde yatışır. Bu söz derde deva olur.',
	'Şaka ve latife, bilgi öğretmeye yarar. Ahmaklar şakayı maskaralık sayar. Ama sen ciddiye al.',
	'Nefis firavundur. Sakın doyurma. Başına kral kesilir.',
	'Aklı gideren sadece şarap değildir. Tüm şiddetli arzular aklı alır. İsyana sürükler. Unutma şeytan Allah ‘a isyan ettiğinde sarhoş değildi.',
	'Beden aç kalmadıkça harekete geçmez, olgunlaşmaz. Tok bedeni ıslah etmek, soğuk demiri dövmeğe benzer.',
	'Dünya uykudaki kişinin gördüğü rüyadır.',
	'Allah akıldan üstün akıl, candan üstün candır.',
	'İnsan görüntüde cihanın parçasıdır. Fakat sen sıfat bakımından insanı, cihanın aslı olarak bil.',
	'Ululara hased edene o hased, ebedi ölüm demektir.',
	'İbrahim (a.s) Allah ‘a ‘Ey Rabbim diriltme gücünü görmek isterim ‘dedi. Allah ona ‘Dört kuş al. Onları öldü r ve etlerini bir havanda döv, sonra etlerinden birer avuç alıp dört ayrı dağa koy. Ardından o kuşları kendine çağır. Sana uçarak gelecektir. ‘ dedi. İbrahim yaptı ve Allah’ın diriltme gücünü apaçık gördü.',
	'Sen bunu sadece kuş diriltme olarak anlarsın öyle mi? Hayır. O şu demekti: ‘Ey İbrahim bedeninde saklı olan ve senin gerçek âleme dirilişine engel olan dört kuşu öldür de sende başka bir âlem dirilsin. O dört kuş; Kaza benzeyen Hırsın, Horoza benzeyen Şehvetin, Tavusa benzeyen Makam tutkundu. Öldür onlar ı da Rabbinin bedeninde neleri dirilttiğini apaçık gör!',
	'Yavaşlık Allah ışığıdır. Çabukluk Şeytanın dürtmesinden meydana gelir.',
	'Kâfirler Muhammed ‘e gelip misafir oldular. Dehşet yemek yediler. Hizmetçiler parmak ısırdı. Bir kişi, yedi kişilik yiyordu. Onl ardan biri Muhammed ‘de geceledi. Hizmetçi kâfire kızıp kapısını kilitledi. Adam yemeğin tesiri ile gece ihtiyaç gidermek istedi. Kapıyı açamadı .Uyudu kaldı. Gece yatağına bilmeden yapmıştı. Peygamber o mahcup olmasın diye sabah görünmedi, adam çıkıp gitti . Peygamber o yatağı temizlemeye koyuldu. Hizmetçiler yapma dedilerse de dinlemedi Allah ‘ın Elçisi.',
	'Aradan az zaman geçmişti ki, kâfir yanındaki minik putunu yatakta unuttuğunu anladı. Geri döndü. Bir de ne görsün? Kâinatın efendisi yatak temizliyor. Hemen şehadet getirdi. Diz çöktü mümin oldu. Peygamber hizmetçilere döndü: ‘Anladınız mı neden ben temizledim?’ dedi. O kâfirle birlikte kabilesi de Müslüman oldu.',
	'Nice düşmanlık var ki, sonu dostluğa çıkar. Nice dostluk var ki sonu düşmanlığa çıkar.',
	'Bulut ağlamadıkça yeşillik güler mi, çocuk ağlamadıkça süt pınarları coşar mı? Çok ağlayınız ki Allah ‘ın rahmet pınarları coşsun. Nebi neden ‘Çok ağlayın’ dedi anla artık.',
	'Alemin direği güneşin harareti ile bulutun ağlamasıdır.',
	'Akıl güneşini yak da gözünü buluta dönüştür.',
	'Aklı bir dostun aklına dost et de ‘Onların işi danışmaktır’ ayetini oku, ona göre iş yap.',
	'Takdir kadısının önünde bela ve elest davalarının görülmesi için bulunuyoruz.',
	'Namaz, Oruç ve Cihad, imana tanıktırlar. Zekât ve sadaka da bu sırrı kendinden haber vermektir. İhsan etmek, doyurmak ‘Ey ulular biz sizinleyiz’ demektir.',
	'Yağmur, pis şeyleri arıtmak için gökten yağar. Suda binlerce ilaç gizli. Ağaçlara gider meyve olur, içilir ilaç olur, deniz olur gemileri taşır. Yeryüzünün yetimlerini su besler.',
	'İş ve söz; İçin tanıklarıdır. Bu ikisine bak da kendi içini tanı.',
	'Şeytan dünyaya âşıktır. Kör ve sağırdır. Bir aşkı ancak başka aşk giderir. Karnına hırslı isen yemek ye, nefsin gelişir. Ama sen kalbine hırslı ol, kalp gıdaları al da ruhun gelişsin.',
	'Sofi saflığı dileyen kişidir. Sofilik sof elbise ile terzilikle ve yavaş yavaş yürümekle olmaz.',
	'Susuz ve acizin ağlaması, soğuk ve ruhsuz kişinin ağlamasından farklıdır. Yakub ‘un ağlayışı Yusuf’u kuyuya atan kardeşlerin ağlaması ile birdir diyebilir misin?',
	'Dua ederken Allah ‘a ezik biçimde el kaldır. Allah’ın merhameti ezik kişiye doğrudur.',
	'Kış olursan baharın gelişini, gece olursan gündüzün gelişini müşahede edersin.',
	'Düşman olmasa savaşa imkân yoktur. Şehvet olmasa ondan kaç denir mi? Şehvet, hırs olacak ki hak-batıl savaşının anlamı olsun.',
	'Sabretme cefasına uğramadıkça karşılığında bir şey elde edemezsin.',
	'La kılıcı ile Allah dışında her şeyi kes at. İlla ‘dan sonra zaten sadece Allah kalır.',
	'Kâmil aklı, aklına arkadaş et de aklın kötü huylardan vazgeçsin.',
	'İnsan kimi severse ona eştir.',
	'Tevbesiz ömür; baştan sona can çekişmedir.',
	'Kim bu âlemden bir ab-ı hayat elde ederse, ölüm ona başkalarından daha çabuk gelip çatar.',
	'Nerede vasıtalar artarsa hedefe ulaşmak orada zorlaşır.',
	'Peygamber, ‘Üç kişiye acıyın; Cahiller arasında kalmış âlime, zenginken fakir düşene, kavmin ulusu iken aşağı hale düşene ‘dedi.',
	'Suçu olan tevbe eder, yolu kaybeden ah eder.',
	'Kimi zıddı ile bir araya koyarsan onu ölüm azabına atmış olursun. Ruh, doğan kuşudur, ten ise kuzgun. Kuzgun leşlere, doğan saraylara layıktır. Kuzgunla yaşamak, doğana eziyettir.',
	'Peygamber ‘Allah suretlerinize bakmaz kalbinize bakar, kalp işlerinizi düzene koyun’ dedi.',
	'Şehvet soy üretmek için olmasaydı, Âdem utancından kendini hadım ederdi.',
	'Kişinin hekimi Allah Nuru olursa, ona ateş ve ihtiyarlık hastalığı zarar veremez.',
	'‘Ölüden diri çıkarır’ ayetini iyi düşün.Yokluk ibadet edenlerin ümididir. Ambarı boş olan ekinci, yoklukla neşelenir de dolma ümidi taşır. Yokluk, Allah sanatının hazinesidir.',
	'Zamanede üç yoldaş var: Biri vefakar, ikisi gaddardır. Biri dostların, öbürü malın mülkün… Bu ikisi vefasızdır. Üçüncüsü ise iyi işlerdir. Vefalı olan da budur. Ötekiler ölünce gelmezler peşinden.',
	'İnciyi sedefin içinde ara, sanatı sanat ehlinden iste.',
	'Can, yokluk bilgisini bir candan beller. Bu bilgi defterden ve dilden bellenmez.(Tasavvufta can ehli bir şeyhe tutun).',
	'Bütün dertlerini tek dert yap. Din derdini dert edinirsen Allah seni diğer dertlerden kurtarır.',
	'Adalet nedir? Ağaçlara su vermek. Zulüm nedir, dikenlere su vermek. Adalet bir nimeti yerine koymak demektir, her su içen tohumu sulamak değil. Zulüm bir şeyi yerinde kullanmamak, layık olmadığı yere koymak demektir. Bu da ancak belaya vesile olur.',
	'Sürme göze çekilir bedene değil. Gönül işini bedenden istemek yanlıştır. Onu kalpten iste.',
	'Yolcu isen yol açarlar.Yok olursan sana varlıkla yönelirler.',
	'Mal mülk, bez gibidir. Hırs ise yara. Kimin hırsı fazla ise yarası fazladır.',
	'Aşk vefakâr adamı satın alır. Allah ‘a kulluk sözünü tut da aşk parlasın.',
	'İlminle gururlanma da ahdini tutmaya bak. İlim kabuktur, ahit iç.',
	'Mizaç ve tabiatı bozuk hasta; insanların iyileşmemesini ister.',
	'Sözün çoğu bizlik ve benlik davasıdır. Az konuş.',
	'İçteki şey dile dökülürse iç yok olur gider. Çok anlatma da için saklı kalsın yok olmasın.',
	'Az söyleyende derin bir iç vardır.',
	'İnsan adamakıllı çalışmaya kul olmalıdır. Çünki bir şeyi ancak çok arayan bulur.',
	'Hırs, çirkinleri güzel gösterir. Bu yolda afetlerin en kötüsü şehvettir. Şehvet nice iyi isimleri kötüye çıkardı, nice akıllılar onunla şaşkın ve aşağılık oldular.',
	'Şehvet yemekten olur, az ye. Yahut bir kadın nikâhlayarak kaç kötülükten.',
	'Hırs ve tamah seni azdıran bir düşmandır.',
	'Taneyi az ye. ‘Yiyiniz ‘emrini okudunsa ‘israf etmeyin’emrini de gör.',
	'Akıllı kişi dünyanın gamını yemez, nimetini yer. Bilgisizler ise pişmanlık içinde mahrum kalırlar.',
	'Dostun sana düşmanlık eder, haset ve kinini dışarı vurursa senden yüz çevirdi diye feryat etme. Kendini ahmak ve bilgisiz hale düşürme. Allah ‘a şükret, yoksullara ekmek ver ki onun çuva lında eskimedin yıpranmadın. Ebedi dostun Allah ‘tır.',
	'Melek; Allah merhametinin madenidir. Şeytan kahır madenidir.',
	'Allah ‘ım sen kimi dertle hasta etmek dilersen ona ağlayış kapısını kapatırsın. Kimi de beladan kurtarmak dilersen gönlüne sızlanma ve ağlayı ş verirsin.',
	'Allah üstünlük bakımından göz yaşını şehitlerin kanı ile eş tuttu.',
	'Gizli lütuf kahırlar içindedir. Değer biçilmez akiğin pislik içinde oluşu gibi.',
	'Hiçbir ölü öldüğüne hayıflanmaz, sadece azığının azlığına hayıflanır. Ölen kuyudan ovaya çıkmış demektir.',
	'Uyku ve uyanma bir nevi küçük mahşerdir.',
	'Taş taşlıktan geçmedikçe parmaklara yüzük olamaz. Yüzük olmak dileyen taş, ezilmeyi, yontulmayı göze almalıdır.',
	'Kötü zanda bulunan kişi çirkindir. Aslında o kendi içini vurur karşıya.',
	'Beden kuyunu kaz da suya ulaş.',
	'Kim zahmet çekerse defineyi elde eder.',
	'Secde ve rüku varlık tokmağını Allah kapısına vurmaktır. Çok vur, mutlaka açılır kapı.',
	'Peygamber ‘Kim kendini bilirse Rabbini bilir’ dedi.',
	'Allah ‘ın kahrı vebaya, lütfu da sabah yeline benzer. Biri demiri çeker öteki saman çöpünü. Allah, doğru kişileri doğru yola kadar çeker, batıl olanlar batılları çekerler. Mide helva severse helvayı çeker. Safraya mensupsa sirkeyi çeker.',
	'Madem ki rızkı taksim eden O ‘dur, o halde şikâyet küfürdür. Sabır gerekir. S abır, genişliğe ulaşmanın anahtarıdır. Allah ‘tan başka herkes düşmandır. Sen asıl dostu düşmanlara şikâyet eder, halinden sızlanırsın öyle mi? Padişah köleye şikayet edilir mi?Akıllı ol.',
	'Kim sabrederse rızkı gelir ona. Aşırı hırsla çalışma ve çabalama sabırsızlıktır.',
	'Kötülük insana tamahtan gelir. Kanaatten kimse ölmedi, hırsla da kimse padişah olmadı.',
	'Allah ‘a şükür, rızkı artırır.',
	'Münafığın özrü kabul edilmez. Çünkü o özür dilindedir kalbinde değil.',
	'Kadınlarda hayvani sıfat fazladır. Çünkü kadın koku ve renge fazlaca meyleder.',
	'Sabır, demir kalkandır.',
	'Ten midesi insanı samanlığa çeker, gönül midesi reyhana çeker. Ot ve arpa yiyen kurban olur, Allah nuru ile nurlanan Kuran olur. Senin yarın pislik, yarın da misktir. Kuran ‘la miskini artır.',
	'Çalış çabala da nura ulaş. Pekmez içinde ne kaynatılırsa pekmez lezzeti alır. Havuç, elma, ayva, ceviz pekmezde kaynasa pekmez tadı alır. Bilgi nura karışırsa inatçı ve kötü kişiler bile bilgiden nur bulurlar.',
	'Tutalım ki Ali ‘den Zülfikâr sana miras kaldı. Sende Ali kolu ve kalbi yoksa Zülfikar neye yarar ki?',
	'Mideyi bırak da gönül tarafına salın. Salın da Allah ‘tan perdesiz selam alasın.',
	'Acele şeytan hilesidir, sabır ve tedbir Allah lütfu.',
	'Şeytan tabiatı bakımından insana düşmandır. İnsanın helak oluşuna sevinir o.',
	'Yılan insanın sadece canını alır. Kötü arkadaş cehenneme sürer de ebedi hayatını mahveder.',
	'İnsan dostunun huyunu alır.',
	'Kim benliğinden kurtulursa bütün benlikler onun olur. Kendisine dost olmayan herkese dost kesilir. Nakışsız ayna olur, tüm nakışlar onda seyredilir.',
	'Hırs insanı kör ve ahmak eder. Bilgisiz hale sokar da ölümü kolaylaştırır.',
	'Açlık, ilaçların padişahıdır. Hekimler niye perhiz verir düşünsene.',
	'Açlık Allah hası adamların gıdasıdır.',
	'Gönül nuru olmayan gönül, gönül değildir. Bedende ruh yoksa topraktır.',
	'Nefsinin istediğini yapıp da bir de ‘inşallah ‘demek Allah’la alay etmektir. Kimi kandırıyorsun?',
	'An be an sana gelen bu dertler, yaptıklarının cezasıdır.',
	'İyi olan her gidişin bir tehlikesi vardır.',
	'Vesvesenin ağzını ancak aşk bağlar.',
	'Ölüye karşı aşk ebedi olamaz. Kişi ölünce aşk biter. Sen ebedi diri olana âşık olmaya bak.',
	'İnanmış o kimsedir ki; her hususta kâfir bile onun imanına hased eder, özenir.',
	'Bebekler cansız oyuncaklarla oynar. Surete taparlar. Hıristiyanlar kilisede İsa resmine taparlar. Müminler Muhammed ‘in suretini hiç merak etmezler. Müslümanlık, suret değil özdür.',
	'Gönlüne belalar geldikçe gülerek karşıla. Şükrü ve sabrı öğreniyorsun, korkma rıza makamı yakın sana.',
	'Allah sırları meydana çıkarır. Mademki bir gün yerden bitecek, niye kötü tohum ekersin?',
	'Çektiğin zahmet, yaptığın suç sonucudur. Sana inen tokat, şehvetinin sonucudur.',
	'Hışmı, şehveti, hırsı terk etmek erliktir. Bu; Peygamberlik damarıdır.',
	'Zahid işin sonunu düşünür, Arif işin başından sonunu görür, onlar son kaygısından kurtulmuşlardır.',
	'Gaflet, küstahlıktan meydana gelir.',
	'Akıl, ecelden titrer durur. Aşk ise neşe içindedir.',
	'Kendi huyundan ayrılırsan, zehir küpünden dahi içsen sana bal olur.',
	'Halk eldeki hazır zevkini put edinmiştir. Özetle halk oyunu kaybetmiştir.',
	'Sır, ancak sırrı bilenle eşittir. Sır, onu inkâr edenin kulağına söylenmez.',
	'Köpekler havladı diye, kervan yoldan kalmaz.',
	'Herkes yaratılışına göre hizmette bulunur.',
	'Leş bize göre kötüdür, pistir. Ama domuz ve köpek için şekerdir.',
	'Âlem baştan başa savaştan ibarettir. Zerre ile zerre, adeta müminin kâfirle savaşı gibi savaşır durur.',
	'Yok olmak zıddın zıddını yenmesinden ileri gelir. Zıt yoksa ebedilik vardır. Allah cennettenzıtları giderdi, orada güneş de yok zemheri de.',
	'Renklerin aslı renksizlik, savaşların aslı barıştır.',
	'Gamlarla dolu dünyanın aslı o âlemdir. Her ayrılığın sonu da buluşmadır.',
	'Manâ denizine susamış isen Mesnevi Adası ‘ndan denize bir ark aç. Mesnevi arkından gidersen denizlerin altını, mercanları görürs ün.',
	'İyilik arayanda kötülük kalmaz.',
	'Sperm erkek bedeninde kaldı mı kokuşur ve pis kalır. Ama candan bir eşe ulaştı mı hayat olur, cıvıl cıvıl bir can olur.',
	'İnsanların kanadı himmettir .',
	'Gül dalı nerede yeşerirse yeşersin güldür. Şarap küpü nereye konursa konsun şaraptır. Gül mezbelelikte bitmekle kötü olmaz, şarap altın tasa konmakla helal olmaz.',
	'Mesnevi bir merada yayılan türlü hayvanları seyre benzer. Sen o hayvan ve örneklere takılma, merayı ve kendini seyretmeye çalış.',
	'Hünerli bilgili kişi iyidir. Ama unutma, İblis de cinlerin en âlimi idi. Bilgili diye insanlara çok da tapma.',
	'İnsan kulaktan gelişir. Duya duya dinleye dinleye can bulur. Hayvan ise mideden gelişir .',
	'Peygamber; ‘Allah’tan cenneti isteyen, insanlardan bir şey istemesin’ dedi.',
	'Bu dünya tuzaktır. Taneleri istek. Tanelerden kaç, tuzağa düşme .',
	'Tereddüt, bir kudrete delalet eder.',
	'Kadere az bahane bul. Suçunu niye başkalarına yüklemeye çalışırsın?',
	'Zahmetin sebebi, kötülük etmektir.',
	'Ölünce değil mi ki çenen bağlanacak, o halde çeneni az oynat.',
	'Çocuk oyuna öyle bir dalar ki gece olduğunu fark etmez bile. Hatta eşyalarını çalsalar onu da fark etmez. ‘Dünya hayatı oyundur.’ sözünü iyi düşün.',
	'Akıllılığa doydum, ben artık deliliğe aşığım.',
	'Arayan nihayet bulur, kurtuluş sabırdan doğar.',
	'Surete bakarsan Mesnevi seni saptırır. Manâya bakan ise Mesneviden yeni bir yol bulur.',
	'‘Ya’ diye uzakta olana seslenilir. Allah şah damarımızdan daha yakın. Hâlâ ona ‘Ya’ diye mi seslenirsin?',
	'Ölmedikçe can çekişme bitmez. Merdivenler bitmeden dama çıkılmaz.',
	'Ölmeden önce ölen birini görmek dilersen Hz. Ebubekr ‘e bak.',
	'Aciz olanı acze düşüren var. Acz bir zincirdir. Gözünü aç zinciri takanı gör.',
	'İki görmek şaşı gözün işidir. Yoksa evvel de aynıdır ahir de. Batın da aynıdır Zahir de…',
	'Dünya pazarının sermayesi altındır. Öte âlemin sermayesi ise; aşk ve ıslak iki göz.',
	'Yücelere daha fazla bela gelir. Çünkü Sevgili, güzellere daha çok cilve eder.',
	'Nefis atının kuyruğu şehvettir. Ona tapan, geri geri gider. Şehvetini kesersen yeni bir yöne arzu duyarsın. Ağaç dalları yamuk yumuk yetişirse uygun yerlerden budarlar da doğru sürer dallar. Şehvetini sürekli buda ki, beden ağacın güzel dallar yaysın .',
	'Define yıkık yerlere saklanır. Sakın ola fakir ve dertlilerin kalbini kırma, ahlarını alma.',
	'Yavaşlıkta rahmet var. Allah ‘Ol’ derse olur, ama insanı güzel bezemek için işi dokuz ayda yavaş yavaş yapar.',
	'Söz,dinleyene göre söylenir. Terzi elbiseyi bedene göre biçer.',
	'Zarar etmek istemezsen, işin önüne gözünü kapa da sonuna bak.',
	'Varlık elde etmek için yokluk gerek.',
	'Mimar ev yapmak için boş arsa arar. Marangoz ahşap işi yapmak için ham tahta arar. Saka su satmak için susuz ev arar. Yokluğa dikkat et, onda çok hikmetler var.',
	'Beden hastalanınca sana ilaç aratır. İyileşti mi şeytanlık aratır.',
	'Tatlı sözlü cahil dostun sözüne kanma. O yıllanmış zehire benzer.',
	'Hiçbir şey olmayan bir şey, hiçbir şey olmayan bir şeye aşık olmuş, hiç var olmamış, hiç var olmamışın yolunu kesmiştir. Hepsi hayal. Ya gerçek?!..',
	'Dertten şikâyeti kes. O seni yokluk hazinesine götüren bir attır.',
	'Zikir fikri titretir, harekete geçirir. Zikri fikrine güneş yap .',
	'Kabul edilmek ya da reddedilmekle aklını meşgul etme. Sen emredileni yap yasaklanandan kaç o kadar!..',
	'Gözündeki tozu temizlersen bir damladan Dicle ‘yi görebilirsin.',
	'Parçalar bütüne tanıktır. Gurubdan sonraki kızıllık, güneşin varlığını söyler.',
	'Karınca bir tane buğdaya ömrünü harap eder. Oysa o taneye bakıp harmanı görse, taneye titrer durur muydu?',
	'Her dükkânın ayrı bir sanatı ve kârı vardır.',
	'Mesnevi yokluk dükkânıdır oğul. Kunduracıda deri olur. Terzide kumaş olur. Mesnevimiz vahdet dükkânıdır. Orada tevhidden başka ne görürsen puttur.',
	'Mezarda ölüyü çok gördün. Bir de ölüde mezarı gör ey kör kişi.',
	'Gönlüm bağdır, gözüm bulut. Bulut ağladı mı bağ yeşerir.',
	'Mum gibi yaş dök ki gönül evin aydınlansın.',
	'Ana veya baba surat asmasa, çocuk tehlikelerden korunur mu? Rabb ‘ın sana bela verdi ise seni tehlikeden çekip almak içindir. Kızacak mısın O’na?!..',
	'Gülmek ağlamada gizlidir. Zevk, gamda gizlidir.',
	'Ağzını açtın mı çıkan söz, artık senin değildir .',
	'Yoksullardan, dertlilerden dua iste. Define yıkık yerdedir dedik ya…',
	'Vaizin sözünün güzelliği dinleyicinin samimiyetindendir. Öğretmenin ilim aşkı talebenin can kulağı ile işe sarılmasındandır.',
	'Gayba haberlerini dinleyen Peygamber, kulağı olmasa Vahiy gelmezdi.',
	'Acı imtihanı rahmet bil.',
	'Bilgi ve hikmet, doğru yolla yolsuzluğu göstermek içindir. Her taraf düzgün yol olsaydı hikmetin de bilginin de anlamı olmazdı.',
	'Heva ve hevesi terk etmek acıdır. Ama Allah ‘tan uzak kalmak daha acıdır.',
	'Her sevgili aşığından haberdardır. Aşık olmuşsan Allah senden haberdardır.',
	'Talebelik eden, üstad olur.',
	'Şehirlerde kuduz köpekler çok olur. Köyler ve yıkık yerler daha emindir. Define de oralardadır.',
	'Allah ‘ın yücelten ve alçaltandır. Kâinata bak yeri alçalttı da göğü yü kseltti.',
	'Kurban mümine sevinç, Öküze helaktir. Kıyamet de öyledir. Kâfire yıkım, mümine cennet.',
	'Nefsiyle savaşmak alçak adamın işi olamaz. Eşeklere Misk sürüldüğünü gördün mü hiç?',
	'Kadına cihad emredilmedi. Nefisle savaşmak onun için onların işi olamaz.',
	'Nadir kadınlar nefsi yenip yüceldiler. Meryem de kadındı ama Meryemler çok nadir çıktılar .',
	'Adalet; layığını yerine koymaktır. Külahın yeri baş, ayakkabının yeri ayaktır.',
	'Dünya; Allah ‘ın kahır yurdudur .',
	'Allah adaleti, herkesi çift yarattı.',
	'Cebrail ‘e ca n olanların kıblesi sidre, karna kul olanların kıblesi sofradır. Arifin kıblesi vuslat nuru; filozofun kıblesi hayaldir.',
	'Zahidin kıblesi Allah, tamahkârın kıblesi ise altın kesesidir.',
	'Manâya yönelenlerin kıblesi sabır, görüntüye tapanların kıblesi bedendir. Batın alemine kanat açmak dileyenlerin kıblesi Allah, Zahir ‘de kalanların kıblesi güzel kadın yüzüdür .',
	'Elde etmen gecikirse sakın ümitsizlenme. ‘Allah’tan ümit kesmeyin’ ayetini çokça oku.',
	'Tutulmadan, kekelemeden yüzlerce kitap okusan da Allah takdir etmedi ise aklında hiçbir şey kalmaz.',
	'Allah’a kulluk edersen kitap okumasan da bilgiler kalbinden akar gelir sana.',
	'Cömertlik sebepsiz, sorgusuz vermektir.',
	'Kardeşlerinin gönlünde sana kin varsa kuyuda kalman daha iyidir. Allah kardeşlerinin kininden korumak için Yusuf ‘u kuyuya attırdı. Etrafında çekemeyenler, sevmeyenler çoksa kendi kabına çekilmek daha iyidir.',
	'Cahilin eziyetine sabret. Bilse yapar mı?',
	'Ehil olmayanlara sabır; ehil olanın ruhuna ciladır. Nemrut ‘un ateşi İbrahim’in tevekkülünü artırdı.',
	'Allah mumunu üflemeye kalkan bilsin ki, o nur sönmez sadece üfleyen, kendi ağzını yakar.',
	'Yarasaların göz yumması, güneş yok mu demektir?',
	'Bedenin direği lokmadır. Açlık kılıcına ekmek zırhtır.',
	'Allah korkuyu aleme direk yaptı. Herkes can korkusu ile bir işe sarılır. Hamdolsun ki, bu korku var. Olmasa dünyada düzen olur muydu?',
	'Kendinden korkmak az kişiye nasip olur.',
	'Doğru var olmasa yalan olur mu?',
	'İlaç dolapta ilaç olarak durdukça tesir etmez. İçilince tesir eder. Mesnevi rafta durmasın. Okumaya bak.',
	'Düğümü kim bağladı ise en iyi o çözer. Bela Allahtan ‘dır. Öyleyse?…',
	'Ey Hikmetine kurban olduğum Allah. Madem dua istersin öyleyse kabul et.',
	'Kardeş, elini duadan ayırma. Kabul edilmiş, edilmemiş sana ne!. Sen duaya devam et.',
	'Cennetliklerin çoğu ahmaktır. Saf olmaya bak.',
	'Akıl ve mantıktan soyun da hayran olmaya bak.',
	'Şehirliler edep ve zekâ ehli olurlar. Ama garipleri doyurmak, bağış yapmak köylülere nasip olmuştur .',
	'Köylerde her gece misafir vardır. Bereket vardır.',
	'Taş, toprak ve su da gizlice dua eder.',
	'İnsan şerle yoğrulmuştur.',
	'Parlak ve açık söz, gönle ferahlık verir.',
	'Sadaka belayı def eder. Hasta isen, sadaka ile tedavi ol.',
	'Vurmak kötü huyadır. Kilim dövülmez, tozu alınır.',
	'Rüzgâr da canlıdır. Ad kavmine kasırga olur, Süleyman ‘a binek.',
	'Namaz beş vakittir. Ama âşıklar her dakika namazdadır.',
	'Baban tokat atsa da ondan vazgeçmezsin. Allah bir kere vurdu diye neredeyse kâfir olacaksın.',
	'Kutluluk görünce şükret, bela görünce sabret ve sadaka ver .',
	'Allah ‘ın baktığı yer, gönüldür.',
	'Heva ve heves erkeklerin hayzıdır. Erkekler, temizlenmeye bakın.',
	'Aşağılıklara arkadaş olursan seni helak ederler.',
	'Vaktiyle bir kurbağa fareye eş oldu. Fare, kurbağaya’kardeş sesin içimi ferahlatır, ama pek az su dışına çıkarsın. Seni saatlerce bekliyorum. Gel anlaşalım, senin ayağından benim ayağıma ip bağlayalım, benim canım sesini çekince ben ipi çekerim sen gelirsin’dedi. Bir gün fareyi karga gördü ve kaptığı gibi havaya kaldırdı. İpe bağlı kurbağanın da sonu oldu bu havalanma.!..',
	'Peygamber ‘Hamd ve Cömertlik cennetten dünyay a uzanmış dallardır’dedi.',
	'Bedeni her yana çeken, bakıştır. Erkeğe kadın bakışı verilirse sapık olur, kadına erkek bakışı verilirse yine sapık olur. Ama sana Cebrail bakışı verilirse kuş gibi semada yol alırsın. Arşa aşık olursun. Eşek huyu verilirse köşkün sadece ahır olur.',
	'Bulutla sözleşen, sakalara bakar mı artık?',
	'Nimet ve ihsanlara karşı şükret. Fakat sana ihsan eden kişiye de şükret.',
	'Hediye ettiğini geri alan kişi, kusmuğunu yiyen köpeğe benzer.',
	'Tatlı meyve yapraklar,dallar arasında gizlidir. Ebedi hayat da ölümün ardında.',
	'Korkuda yüzlerce eminlik vardır. Unutma, gözümüzün gören kısmı simsiyahtır .',
	'Peygamber dedi ki, ‘Şu iki hırslı hiç doymaz:Dünyayı isteyen ve ilim isteyen.’',
	'Sabır kılavuzu sana kanat açarsa canın arşa, kürsiye kanatlanır.',
	'Sırlara Allah ‘tan başka mahrem yoktur. Ahlara ancak o cevap verir.',
	'İnsana kol-kanat, akıldır. Aklın yoksa akıllıyı kılavuz al, görüşün yoksa görüş sahibine tutun .',
	'Miras malının vefası yoktur, geçer gider. Mirasa konan, kadrini bilmez, çünkü emek vermedi. Sana da Allah bu canı bedava verdi diye kıymet bilmezsin.',
	'Din mahsulünü gözyaşı ile sula.',
	'Hırsız ve kötü adama acımak; zayıf ve yoksulları öldürmektir.',
	'Lezzetin kaynağı açlıktır. Aç olana arpa ekmeği kebap olur, tok olan kebaptan tiksinir.',
	'Kötü kişilerin inkârı olmasa mucizeler olmazdı.',
	'Candan sevilen sevgilinin gerçekliği, kan gibi damarlarda dolaşır.',
	'Dünya mülkü bedene tapanlara helaldir. Biz ise çöküşü olmayan saltanata kul olduk.',
	'Kadının hilesine nihayet yoktur. İblis Adem ‘i kandıramadı da Havva’ya y öneldi. Havva ile ikisini de elde etti .',
	'Ört de senin de ayıbını örtsünler. Kendinden emin olmadıkça kimsenin haline gülme.',
	'Kadının bakışı fitnedir. Bu bakışa bir de sesi eklenirse felaket yüz kat olur. Ona karşı durmak Yusuf ‘ların işidir.',
	'Aşıkların yanıp yıkılması da bir gelişmedir. Nitekim ay da parça parça olarak dolunay olur .',
	'Topraktan biten gül solar. Gönülden biten ebedidir.',
	'Sözün halin olmuş ise kanatlanırsın artık.',
	'Gam mayası ile gayba iman kuvvetlenir.',
	'Boş karın şeytana zindan olur. Onun pazarı, dolu karındır.',
	'Hayat; ölümde ve sıkıntıdadır. En güzel sular karanlık mağaralardan doğar.',
	'Sayılı ömrü Allah ‘a verirsen sayısız ve ebedi hayat elde edersin .'
);
	
add_action("plugins_loaded", "mim_widget_create");

function mim_widget_create() {
	$options = array('classname' => 'mim_widget', 'description' => "Mevlânâ Celâleddin Rumî'nin altı ciltlik Farsça eseri, Mesnevî-i Manevî'den seçme beyitleri Türkçe olarak gösteren bir bileşen." );
	wp_register_sidebar_widget('mim_widget', 'Mesnevi-i Manevi', 'mim_widget_init', $options);
}

function mim_widget_init($args) {
	extract($args);
	echo $before_widget;
	echo $before_title.'Mesnevi-i Manevi'.$after_title;
	mim_widget_show();
	echo $after_widget;
}

function mim_widget_show() {
	global $mesnevi;
	echo '<p>'.$mesnevi[array_rand($mesnevi)].'</p>';
}

add_filter('the_content', 'mim_tag');

function mim_tag($content) {
	global $mesnevi;
	$content = preg_replace('@\[mesnevi-i-manevi\]@', '<div id="mesnevi-i-manevi" style="padding: 20px 6px 0 20px;background: url(wp-content/plugins/mesnevi-i-manevi/images/su.png) no-repeat left top;border: 1px solid #D9D9D9;">'.$mesnevi[array_rand($mesnevi)].'<div style="padding: 0 30px 6px 0;text-align: right;background: url(wp-content/plugins/mesnevi-i-manevi/images/sa.png) no-repeat right top;"><small><i>Mevlânâ Celaleddin-i Rumi</i></small></div></div>', $content);
	return $content;
}
?>